### ISSUE TITLE
QuickMuteChannels requires you to visit the channel first

### ISSUE THREAD

**Issue by ImportTaste** [Strencher/BetterDiscordStuff#10]
I'm guessing it didn't use to work this way, but it does now. No speaker icon shows up next to a channel on any given server until you visit that channel, and once you restart Discord, you have to revisit said channels to get the speaker icon to show back up.

As a sidenote, I think these would better icons to use:
https://www.iconfinder.com/icons/3669224/ic_notes_speaker_icon
https://www.iconfinder.com/icons/3669223/ic_notes_off_speaker_icon
(These are MIT licensed, before their change to Apache 2.0.)

**Comment by Strencher** [comment]
create a pull request

**Comment by ImportTaste** [comment]
Sorry, my knowledge of JavaScript is exceptionally lacking.
