### ISSUE TITLE
[UserBackgrounds] Feature Request: Banner Aesthetics.

### ISSUE THREAD

**Issue by saint2706** [Strencher/BetterDiscordStuff#102]
A feature that shows a user's nitro banner in the member list (and the private DMs list) and if a user does not have a nitro banner, it falls back to the UserBG.

[Pic Related](https://media.discordapp.net/attachments/829445715356024844/887192057288998922/unknown.png)

**Comment by HypedDomi** [comment]
UserBackgrounds isnt maintained anymore
