### ISSUE TITLE
UnreadCountBadges : Settings panel broken

### ISSUE THREAD

**Issue by BluTree** [Strencher/BetterDiscordStuff#109]
Everything is in the title.
I add some screenshots :
![image](https://user-images.githubusercontent.com/11920536/139905994-e8bd4fbe-ee0a-4496-8c69-a0e2026dac5e.png)

![image](https://user-images.githubusercontent.com/11920536/139906017-cf726b8f-b172-4b57-a8df-624d46633260.png)

**Comment by aprzn123** [comment]
I just came across this issue today; I wanted to adjust the settings, but they can't be changed.

**Comment by Strencher** [comment]
Fixed, update the plugin
