### ISSUE TITLE
User Profile Icon at the bottom left dosen't light up green when speaking in a voice chat

### ISSUE THREAD

**Issue by leon-cavanagh** [Strencher/BetterDiscordStuff#110]
As in title, when in a voice chat the user icon at the bottom left doesn't light up green when speaking and having the plugin enabled

I can't really show it not working but here is a screenshot of the plugin disabled and it working when I speak

![Screenshot 2021-11-06 182627](https://user-images.githubusercontent.com/93812750/140599120-1f2ec898-529c-464a-adbd-94f484268872.png)

**Comment by Strencher** [comment]
Fixed already.
