### ISSUE TITLE
[Platform Indicators] not showing platform indicator in DM list

### ISSUE THREAD

**Issue by Poirot12345T** [Strencher/BetterDiscordStuff#111]
after updating Discord to latest version, platform indicators don't show in DM list, even after reloading whole Discord and the plugin itself

To reproduce bug:
PlatformIndicators setting - "show in DM list" (by the way there's a typo in the seting, it says "Dmd list" instead of "DM list")
Update to latest Discord version

Expected behavior:
Indicator shows next to each online/away/DND user in DM list

debug info:
![image](https://user-images.githubusercontent.com/82270962/141157781-0cd687ca-7e92-4514-b244-208973e08d04.png)

**Comment by FarrinOrbs** [comment]
yeah I've noticed this too

**Comment by Jnss98b** [comment]
I have this bug too on the latest discord version

**Comment by Poirot12345T** [comment]
Solved in last push/update, thank you!
