### ISSUE TITLE
Discord crashes when opening people profiles with UserBG 

### ISSUE THREAD

**Issue by AdriGeeK03** [Strencher/BetterDiscordStuff#112]
![image](https://user-images.githubusercontent.com/50402620/141328216-9b564bba-a288-4ad1-9ba6-6d898015751c.png)

**Comment by Strencher** [comment]
Fixed in https://github.com/Strencher/BetterDiscordStuff/commit/3f06903609f847da79fde471c1d4f3d2df4063d2

**Comment by AdriGeeK03** [comment]
Crashes again with the new version of BetterDiscord :/
