### ISSUE TITLE
UnreadCountBadges Server badge is on Home icon

### ISSUE THREAD

**Issue by nearcatch** [Strencher/BetterDiscordStuff#115]
Have some unread messages but the count badge is on the Home icon instead of the server icon

![image](https://user-images.githubusercontent.com/692914/142594088-61ca9812-1f5f-47ee-96c3-3e18ce50a9b7.png)

EDIT: Just noticed today that it's a merged number of all servers. Maybe this is a setting I can't currently change because of #109

**Comment by Strencher** [comment]
No, the counter on guilds was broke but it has been fixed.
