### ISSUE TITLE
[UserBackgrounds] Incompatible with EditUsers custom banner

### ISSUE THREAD

**Issue by fowlis** [Strencher/BetterDiscordStuff#116]
![image](https://user-images.githubusercontent.com/84232621/142757697-1da86c3e-f816-4c42-99a1-c162c5e54f69.png)
This is my custom banner using EditUsers (I know its only local)

When I enable UserBackgrounds, the EditUsers banner doesn't display.
![image](https://i.imgur.com/pVnuvYc.gif)

The only troubleshooting I could think to do was:
• Change the EditUsers banner to a static image rather than a gif
• Disabling both addons and re-enabling
• Deleting and re-downloading both addons
I can try anything else suggested.

Edit: forgot to mention that it was working fine the last time I looked (I don't check it often)
I also have a EditUsers banner on someone else's profile, which stops displaying after I enable UserBackgrounds, even though they don't have a USRBG banner.

**Comment by Elsooh** [comment]
goood

**Comment by Strencher** [comment]
Nothing I can do about it unfortunately.
