### ISSUE TITLE
[OpenLinksInSpecificBrowser] Could not be constructed

### ISSUE THREAD

**Issue by ErdeFB** [Strencher/BetterDiscordStuff#117]
Spits out the following error:

```
1	OpenLinksInSpecificBrowser: Could not be constructed.
2	at Object.initializeAddon (<anonymous>:4:307996)
3	at Object.loadAddon (<anonymous>:4:269972)
4	at Object.loadAddon (<anonymous>:4:307108)
5	at Object.loadAllAddons (<anonymous>:4:272224)
6	at Object.initialize (<anonymous>:4:266714)
7	at Object.initialize (<anonymous>:4:306318)
8	at Object.startup (<anonymous>:4:368333)
```
Doesn't look too useful for me, but maybe it has something meaningful in it for you.

Discord version: 0.0.16-1 / Linux
Better Discord: 1.3.0

If you need any additional information, let me know.

**Comment by Strencher** [comment]
This plugin hasn't been maintained in a long time, I might fix it at some point. I'll let you know.

**Comment by HypedDomi** [comment]
No longer maintained
