### ISSUE TITLE
[Userdetails] causes crashes when powercord's spotify modal is active

### ISSUE THREAD

**Issue by quiet69** [Strencher/BetterDiscordStuff#118]
![image](https://user-images.githubusercontent.com/43907678/144098890-e2d89a1a-32cc-4f02-ac94-bc9d10f600c8.png)

**Comment by Strencher** [comment]
That's actually an issue with that Spotify plugin you have installed. I'm even providing stuff for plugins to inject again.

**Comment by quiet69** [comment]
ok thanks for replying
