### ISSUE TITLE
Some Games not supported?

### ISSUE THREAD

**Issue by DrachTheBro** [Strencher/BetterDiscordStuff#12]
For some reason when someone is playing R6 I can look at the Rich Presence stuff and the "Playing a game" menu. But Mordhau for exemple doesn't work, it's just Rich Presence. 

I don't really know if it's a feature or not. 

![richpresencebug](https://user-images.githubusercontent.com/39418312/97332465-c67ba200-187a-11eb-846d-c7813deabea0.png)

**Comment by Juby210** [comment]
Not all users have more than 1 game at the same time added to Discord.

**Comment by Strencher** [comment]
that isn't possible if discord doesn't show a timestamp

**Comment by DrachTheBro** [comment]
> 
> 
> that isn't possible if discord doesn't show a timestamp

Okay thank you. Very nice plugin 👍
