### ISSUE TITLE
Offline Indicator

### ISSUE THREAD

**Issue by Crni39** [Strencher/BetterDiscordStuff#122]
If you can see offline indicator for yourself on pc/phone, can't ya add that you can see if user has set offline status on purpose and which platform i reallly need that.

> Me, with offline status
![Image](https://user-images.githubusercontent.com/65065580/147858822-eafd66b2-900e-4ee7-b8ae-f2111621c9e9.png)

> Some user with offline status
![Image](https://user-images.githubusercontent.com/65065580/147858877-efe5fec3-d812-4374-924b-5af64c5d7a84.png)

**Comment by Strencher** [comment]
No this is not possible discord doesn't provide this information for other users.
