### ISSUE TITLE
UserBackgrounds banner is not showing up in profile settings of discord.

### ISSUE THREAD

**Issue by IamNickerson** [Strencher/BetterDiscordStuff#124]
Hey,
UserBackgrounds banner is not showing up in profile settings of discord instead the PFP icon in profile is like this in the picture.
![image](https://user-images.githubusercontent.com/61643704/149508305-8db8ba65-fed6-4b71-b74c-c01312a49dd0.png)
Is the issue with the theme I am having or UserBackgrounds?

**Comment by Strencher** [comment]
It's an issue with UserBackgrounds. It broke after the latest discord update.

**Comment by IamNickerson** [comment]
Oh ok is there gonna be a fix?

**Comment by dav1312** [comment]
Just gotta replace `.accountProfileCard-1XCH88` with `.accountProfileCard-lbN7n-`

**Comment by IamNickerson** [comment]
Okay

**Comment by IamNickerson** [comment]
> Just gotta replace `.accountProfileCard-1XCH88` with `.accountProfileCard-lbN7n-`

Is it possible that you can update UserBackgrounds to fix this issue.

**Comment by IamNickerson** [comment]
Ok then. The issue is fixed I self fixed myself thanks to the dav1312 for giving me the code to replace with.
