### ISSUE TITLE
UnreadCountBadges - Cannot see server unread count when using extra column feature in ServerFolders

### ISSUE THREAD

**Issue by playful1510** [Strencher/BetterDiscordStuff#128]
When using DevilBro's ServerFolders plugin with UnreadCountBadges, the unread message count for each server isn't visible when using the 'open folder into extra column' setting enabled. When disabled, counts appear as they should within folders. Counts appear properly on folders themselves and on individual servers at all times.

**Comment by Strencher** [comment]
That is actually a specific issue to ServerFolders.
