### ISSUE TITLE
Doesnt work!

### ISSUE THREAD

**Issue by Naide09** [Strencher/BetterDiscordStuff#13]
https://betterdiscordlibrary.com/plugins/ShowAllActivities
Doesnt work, and i was extremely excited for it! When i download it, it either comes up with failed virus scan or it uninstalls itself when i try to open the folder and move it to plugins! Please help 
![failed](https://user-images.githubusercontent.com/73746891/97804052-491eab80-1c45-11eb-98d4-e8032eedc8d6.png)

**Comment by Strencher** [comment]
the your virus system detects the self-install script (used for idiots who run the plugin file with double click). Ignore that. if it would have a virus the plugin wouldn't be used by many people.

**Comment by Strencher** [comment]
Due to inactivity ill close this.
