### ISSUE TITLE
Suggestion: please reduce the notifications for ShowSessions to "toast" style notifications

### ISSUE THREAD

**Issue by NanoCats** [Strencher/BetterDiscordStuff#131]
If you have a phone, pick it up and look at it for a few seconds, or you have discord set to mark you down as "away" after you leave for 5m it gets annoying fast to have a window pop up that you have to dismiss every time. Like, yeah discord, I know, there's nothing to worry about **from my current session which is me looking at you right now**.

Or maybe a "remember this device" feature, or whatever, I don't know, I had to turn this feature off because it was spawning too many windows.

**Comment by Strencher** [comment]
Actually, I can't make it remember a device, since there's no indication for that. I could add a filter for the current session id but that's all I can do. I also considered having my own notifications smilar to VoiceChatNotifications but I ended up implementing this modal instead.

**Comment by HypedDomi** [comment]
Windows Notifications would be also nice

**Comment by HypedDomi** [comment]
More Notificationmodes exists now
