### ISSUE TITLE
ShowSessions - Blacklist certain users

### ISSUE THREAD

**Issue by PokeDerg** [Strencher/BetterDiscordStuff#132]
I would like to blacklist my phone and main pc from the update notice so i can tell if there is suspicous activity on my account without getting a notification every time i start/stop a game on discord, i would love to be able to hide "this pc" or choose ids to ignore

**Comment by Strencher** [comment]
Well, as I mentioned in the previous issue, it's all handled through sessions and hashes which don't give me a hardware ids or anything, only stuff like the OS, the type & the present status. I can detect the current running session and exclude it, I will also consider doing that at some point.

**Comment by PokeDerg** [comment]
that would be great shame you dont get access to specific devices like phone but look forward to current session being excluded (or setting for it)
