### ISSUE TITLE
[ShowSessions] Enhancement / question

### ISSUE THREAD

**Issue by JustCryen** [Strencher/BetterDiscordStuff#134]
Is it possible to make session updates appear like a small popup, not full screen notifications?
It's a good idea to have the updates enabled in case of malicious activity but every time I open discord on my phone it covers the screen entirely.

**Comment by HypedDomi** [comment]
There is a new Version which lets you change the Notification Style. There are Modal(the default setting), toast and windows Notification. Not sure if he already pushed the update, but on his discord is the new version

**Comment by JustCryen** [comment]
The newest version in the github is 1.1.0 which was pushed 2 days ago.
It's the one I have and it appears like it's not the one you're talking about.
But since it's already being worked on and probably will be pushed in the near future, I think I can close this issue.
Thanks!
