### ISSUE TITLE
Missing copyid button on right click on profile if enabled copier plugin

### ISSUE THREAD

**Issue by daniel-jebarson** [Strencher/BetterDiscordStuff#137]
I used this copier plugin then i noticed  once i enable this plugin the copy id of profiles on right click is not available.

Picture for reference:

Before enabling plugin : 
Below are the options available for me before enabling  this plugin
![image](https://user-images.githubusercontent.com/88134306/152397758-04605330-d02e-413f-a14f-4c758d280b82.png)

After enabling plugin: 
After enabling the plugin the copyid and some other options are missiing
![image](https://user-images.githubusercontent.com/88134306/152398105-e1b040d1-db87-413d-80cf-872b48f12c73.png)
 
So try to fix this issue ASAP

**Comment by XxUnkn0wnxX** [comment]
talk about rude asking for ASAP, if you want it ASAP you might as well pay the guy.

**Comment by Strencher** [comment]
Fixed

**Comment by daniel-jebarson** [comment]
oh thank you (:
