### ISSUE TITLE
[Copier] Copy button duplicates the often I open the context menu (User channel only)

### ISSUE THREAD

**Issue by TheBlackEntity** [Strencher/BetterDiscordStuff#141]
Heyo \o

I'm having an issue with Copier...

If I right click on a dm user, the Copy button duplicates itself everytime I open the context menu.

The more I open the menu, the more the Copy button duplicates

**Comment by Strencher** [comment]
Do you happen to have the ImageUtilities plugin installed?

**Comment by TheBlackEntity** [comment]
> Do you happen to have the ImageUtilities plugin installed?

No, I don't have it installed

**Comment by TheBlackEntity** [comment]
My plugin list:
./UserNotes.plugin.js
./ShowHiddenChannels.plugin.js
./DiscordFreeEmojis64px.plugin.js
./Translator.plugin.js
./CallTimeCounter.plugin.js
./CreationDate.plugin.js
./ReadAllNotificationsButton.plugin.js
./PluginRepo.plugin.js
./SplitLargeMessages.plugin.js
./InvisibleTyping.plugin.js
./PermissionsViewer.plugin.js
./ServerDetails.plugin.js
./BetterFriendList.plugin.js
./StaffTag.plugin.js
./BetterNsfwTag.plugin.js
./ServerCounter.plugin.js
./CharCounter.plugin.js
./EmojiUtilities.plugin.js
./BlurNSFW.plugin.js
./DoNotTrack.plugin.js
./0PluginLibrary.plugin.js
./0BDFDB.plugin.js
./UserVolumeBooster.plugin.js
./BetterBannedUsers.plugin.js
./APlatformIndicators.plugin.js
./SilentTyping.plugin.js
./Apate.plugin.js
./BetterBotTags.plugin.js
./ServerConfig.plugin.js
./FileViewer.plugin.js
./BetterPictureInPicture.plugin.js
./PinIcon.plugin.js
./SendTimestamps.plugin.js
./Freemoji.plugin.js
./DoubleClickVoiceChannels.plugin.js
./BetterInvites.plugin.js
./navigationfix.plugin.js
./BetterMessageLinks.plugin.js
./EditServers.plugin.js
./BDContextMenu.plugin.js
./Hastebin.plugin.js
./GuildAndFriendRemovalAlerts.plugin.js
./GlobalReplies.plugin.js
./ProProfile.plugin.js
./RemoveChatButtons.plugin.js
./NotificationPrompt.plugin.js
./Copier.plugin.js

**Comment by TheBlackEntity** [comment]
Just found the issue...
Seems like BetterFriendList is incompatible with Copier

**Comment by XxUnkn0wnxX** [comment]
![Screen Shot 2022-02-12 at 4 34 22 pm](https://user-images.githubusercontent.com/2242880/153698425-b2a60a97-ef4f-482c-8406-f6e2026547ec.jpg)

I Get this with both BetterFriendList & ImageUtilties

**Comment by XxUnkn0wnxX** [comment]
also at @Strencher there is no copy function in the friend's list even with everything off except for the copier plugin
![Screen Shot 2022-02-12 at 4 47 33 pm](https://user-images.githubusercontent.com/2242880/153698841-543dbe73-4538-4c84-b5f9-d3cb57394bc3.jpg)

**Comment by TheBlackEntity** [comment]
Now it doesn't really work at all when it comes to users in dms...
If I click on "name" most of the time it does nothing, but if it does something, it copies the id.

Trying to copy the "Avatar Url" does nothing.

Dm Id works.

Custom Format doesn't do anything either.

Also, sometimes clickable elements below the context menu have priority over your Copy menu

**Comment by TheBlackEntity** [comment]
There's an error message when trying to copy Custom Format though:
```
Uncaught TypeError: user.getAvatarURL is not a function
    at Object.getValue (Copier.plugin.js:249)
    at Copier.plugin.js:1086
    at Array.reduce (<anonymous>)
    at action (Copier.plugin.js:1085)
    at 94571374b37c183de5fd.js:2087
    at r (3071b9ff12919c9a02ef.js:126)
```

Avatar Url too:
```
3071b9ff12919c9a02ef.js:126 Uncaught TypeError: user.getAvatarURL is not a function
    at Object.getValue (Copier.plugin.js:249)
    at Copier.plugin.js:1086
    at Array.reduce (<anonymous>)
    at action (Copier.plugin.js:1085)
    at 94571374b37c183de5fd.js:2087
    at r (3071b9ff12919c9a02ef.js:126)
```

**Comment by TheBlackEntity** [comment]
All fixed, thank you!
