### ISSUE TITLE
[Platform Indicators] Feature request

### ISSUE THREAD

**Issue by Canada-LaVearn** [Strencher/BetterDiscordStuff#142]
I'm not sure if it is possible, but can you add an option to show the platform indicator in the user profile popout?

**Comment by HypedDomi** [comment]
Like this?
![image](https://user-images.githubusercontent.com/50876016/153498109-1d634185-dd3c-4c1d-83ba-240b9dc923ec.png)


or like this?
![image](https://user-images.githubusercontent.com/50876016/153498281-8b029a4b-2dcf-4fd8-be11-0f50df6c9bb5.png)

**Comment by Satnamigyz** [comment]
Mine shows like this, am I missing some updates or something?
![image](https://user-images.githubusercontent.com/12208188/153714948-418eead1-5ecd-4961-ba8e-5af5e8b1a164.png)

**Comment by HypedDomi** [comment]
No. Strencher removed the Online Indicator Thing.

**Comment by Canada-LaVearn** [comment]
> Like this? ![image](https://user-images.githubusercontent.com/50876016/153498109-1d634185-dd3c-4c1d-83ba-240b9dc923ec.png)
> 
> or like this? ![image](https://user-images.githubusercontent.com/50876016/153498331-7c6e9d74-c798-40aa-af9e-d5c95acc402e.png)

My question was specifically asking for the first one, but the second one could be nice as an option as well!

**Comment by HypedDomi** [comment]
Already build in. 2. Option got removed because it was to hard to maintain
