### ISSUE TITLE
(BetterRoleColors) Role color only changes for certain people

### ISSUE THREAD

**Issue by Sertule** [Strencher/BetterDiscordStuff#144]
When using Better Role Color, the color in the profile only changes for certain members.

![image_2022-02-11_222453](https://user-images.githubusercontent.com/95261381/153694926-1f2a40b1-4226-4f50-bd25-4d8259f98867.png)

![image_2022-02-11_222500](https://user-images.githubusercontent.com/95261381/153694932-56df32e7-3983-4041-84d1-891c50ff9432.png)

**Comment by HypedDomi** [comment]
Not a plugin from Strencher
