### ISSUE TITLE
(PronounDB) Pronoun editor not showing up in context menu

### ISSUE THREAD

**Issue by Lunascaped** [Strencher/BetterDiscordStuff#145]
The pronounDB option no longer shows up, meaning I can't add, change, or remove pronouns. The ones I set still show up and work however.

**Comment by DinoTymo** [comment]
Same for me.
Only pronouns from the [PronounDB website](https://pronoundb.org/) work, but I can't edit them locally anymore...

**Comment by diegofelly** [comment]
Same thing has been happening for me

**Comment by Joeeeeeeey** [comment]
> Seems to be fixed for me now, so maybe try deleting the file and reinstalling it

Nah, mine is still not allowing me to do so. This issue still needs to be addressed.

**Comment by DinoTymo** [comment]
Started working for me

**Comment by HypedDomi** [comment]
Broken due the recent Discord Update. Please use #296
