### ISSUE TITLE
Unreadcountbadge don't work on my Guild

### ISSUE THREAD

**Issue by Soulivan71** [Strencher/BetterDiscordStuff#146]
![image](https://user-images.githubusercontent.com/36502190/154195708-ce250159-84e0-4c45-91f6-c900bb4f9214.png)
![image](https://user-images.githubusercontent.com/36502190/154195721-bcad2664-abd4-41d2-959b-e725de41a9a4.png)
![image](https://user-images.githubusercontent.com/36502190/154195761-96b1e8d7-0f4c-462a-9ed9-9acd4b748edc.png)
It appears on folders, but not on guilds

I have the version 1.2.0

**Comment by HypedDomi** [comment]
Should be fixed. If not, reopen this issue

**Comment by Soulivan71** [comment]
Yes thx
