### ISSUE TITLE
Doesn't change anything :(

### ISSUE THREAD

**Issue by AwsomeCreeper9** [Strencher/BetterDiscordStuff#15]
The ShowAllActivities Plugin doesn't show all activities, just ONE. No arrows to flip between them, just 1 activity.

I have 2 things open, one called Test 1 and one called Test 2 in game activity, it only wants to show one of the things
![image](https://user-images.githubusercontent.com/74505552/99191969-cc57fb00-2735-11eb-83aa-010c59ed4bdd.png)

**Comment by Strencher** [comment]
Sorry for the very late response. Discord doesn't show the same games twice. I know that there's a difference between the name, but basically they are the same unkown games.

**Comment by Strencher** [comment]
Closing the issue due to inactivity.
