### ISSUE TITLE
Fix for Alexis Modern Discord Theme

### ISSUE THREAD

**Issue by Just5KY** [Strencher/BetterDiscordStuff#151]
Plugin does not show up in this Theme
![image](https://user-images.githubusercontent.com/71321862/154696890-fe8ef4ba-92c8-49aa-8a88-bd124d4edf14.png)

To recreate this issue
1. Install Alexis Modern Discord Theme
2. Install custom css fix

```
@import url("https://onkofonko.github.io/theme/fixedsource.css");
@import url("https://onkofonko.github.io/theme/fixes.css");
```

**Comment by Strencher** [comment]
This is actually an issue with the theme. Nothing I can do about it.
