### ISSUE TITLE
Statuses Everywhere currently breaks the offset of PFPs in chat

### ISSUE THREAD

**Issue by Milk-3000BPM** [Strencher/BetterDiscordStuff#156]
Enabling statuses everywhere makes all pfp's in chats slide downwards by about the space of one pfp and leaves a grey square behind it and it looks really icky and bad. Hopefully it's an easy fix, this is one of my favorite plugins.

**Comment by imthatguyhere** [comment]
#162 has some good images.

**Comment by elijaholmos** [comment]
experiencing this as well

**Comment by HypedDomi** [comment]
Paste this into your custom CSS
```css
.avatar-2e8lTP:before {display: none;}
```

**Comment by moontai0724** [comment]
This is webpack compiled production code, totally not real open-sourced. It can't be community contributed even if we want to help fix this problem. Will you consider open source to let communities help improve this?

**Comment by voidfill** [comment]
go to dev branch for uncompiled.

**Comment by moontai0724** [comment]
> go to dev branch for uncompiled.

Wow, sorry for my misunderstanding, let me check it out.

**Comment by Strencher** [comment]
Should be fixed in the latest version.
