### ISSUE TITLE
profile pictures💀 

### ISSUE THREAD

**Issue by xdjoee** [Strencher/BetterDiscordStuff#159]
![xxxxx](https://user-images.githubusercontent.com/69331937/157511203-76633cf7-2357-491e-a6f1-d8ca461e7f3a.png)

**Comment by TheLostChallenger** [comment]
Experiencing the same thing

**Comment by TheLostChallenger** [comment]
Wait, you have to put this line of code in it

 .avatar-2e8lTP:before {display: none;}

**Comment by HypedDomi** [comment]
The Problem is already reported in #156

**Comment by Strencher** [comment]
duplicate of #158

**Comment by notnicknamed** [comment]
Hello. I would like to report I am having a similar problem.
