### ISSUE TITLE
Detected by McAfee

### ISSUE THREAD

**Issue by bangtothepow940** [Strencher/BetterDiscordStuff#16]
When I scanned the plugin to VirusTotal, it was detected as "BehavesLike.VBS.Dropper.zv". Is it normal?

The detection is [https://www.virustotal.com/gui/file/ce24d731cebc7e2e68718ad8d4cab1148e3c228b2ec587054b1d36fc45e5c88c/detection](url)

**Comment by Strencher** [comment]
That is because of the self install script, which is there because people are always trying to run our plugins directly with double click, but that just throws errors.

**Comment by bangtothepow940** [comment]
Ok, Thanks! :D
