### ISSUE TITLE
Proifle Pictures are no longer where they were. (Still unfixed)

### ISSUE THREAD

**Issue by TheLostChallenger** [Strencher/BetterDiscordStuff#160]
![image](https://user-images.githubusercontent.com/101287851/157513412-3bb8a7d5-50b0-4214-85cd-332bd92c98a4.png)

I've looked through all my plugins, for whatever reason, this plugin seems to be the cause

**Comment by HypedDomi** [comment]
You can use this as temp fix
```css
.avatar-2e8lTP:before {display: none;}
```
The Problem is already reported in #156

**Comment by jvyden** [comment]
For reference, the plugin causing the problem is StatusEverywhere v2.3.2.

**Comment by jvyden** [comment]
Oops, didn't realize this was a duplicate. Apologies.

**Comment by Strencher** [comment]
duplicate of #158
