### ISSUE TITLE
StatusEverywhere

### ISSUE THREAD

**Issue by VargentSomnium** [Strencher/BetterDiscordStuff#162]
Looks like statuseverywhere is broken in either the new update or just conflicts with something in discord. 

![image](https://user-images.githubusercontent.com/52584900/158451347-9d47c1e6-ee81-4b96-a089-795c8dfa78a8.png)
![image](https://user-images.githubusercontent.com/52584900/158451413-0b70c61e-08f9-40b1-8f31-52b06eea6bc6.png)

No theme / extra plugins
![image](https://user-images.githubusercontent.com/52584900/158451612-b884770a-e757-4748-a78d-acc8d552b515.png)
![image](https://user-images.githubusercontent.com/52584900/158451650-fd1cea37-da4a-41eb-b5ee-23d4688e49be.png)

The profile popout with out themes or plugins is fine. That I'm pretty is just css problems but the alignment in the chat I'm not sure of.

**Comment by IamNickerson** [comment]
https://github.com/Strencher/BetterDiscordStuff/issues/158

**Comment by IamNickerson** [comment]
Go to this issue it will tell what will be the fix for it

**Comment by HypedDomi** [comment]
Fixed
