### ISSUE TITLE
(PronounDB) Userlist "Flyout" card flickering (Conflict with BetterRoleColors)

### ISSUE THREAD

**Issue by Zacam** [Strencher/BetterDiscordStuff#169]
Discord Version: Stable Branch, 121017
BetterDiscord Version: 1.5.2
PronounDB Plugin Version: 1.2.1
BetterRoleColors Plugin Version: 0.8.17

After disabling all other addons/themes (save the mentioned one):
PronounDB enabled on discord start/reload will cause for some (but not all) flyout cards to flicker width-wise like it's trying  to redraw.
(Regardless of flying out from Chat or Memberlist, though it doesn't always happen to -all- user flyouts, usually those with a lot of roles/program statuses or Discord Sharing enabled)

Its almost similar to the redraws that happens with the plugins for "Account Created", "Joined Date" and "Last Message" as it updates the flyout card; but testing was done with those plugins disabled.

Current Workaround:
Disable PronounDB, view a flyout card, re-enable PronounDB; or turning off BetterRoleColors

This workaround only works until the next time Discord is reloaded/relaunched.
If BetterRoleColors is toggled while PronounDB is enabled, the problem will re-occur until PronounDB is toggled.

**Comment by Zacam** [comment]
As a side note: Toggling PronounDB to resolve the redrawing issue caused by the BetterRoleColors conflict will cause the Pronoun DB context menu's to no longer render in the Right-Click context menu's on users/profiles/chats; but it's the only way to avoid the flickering redraw, as starting Discord with BeterRoleColors disabled and then enabling it will immediately cause the flickering until PronounDB is toggled in the instance.

**Comment by Strencher** [comment]
This is actually an issue with discord itself as they re-render the UserPopout very frequently, but since the PronounDB tag is loaded through a DB asynchronously, it takes a couple seconds to load it. Please wait until discord's developers fix this issue.
