### ISSUE TITLE
UnreadCountBadges.plugin.js crash discord

### ISSUE THREAD

**Issue by vovklosev** [Strencher/BetterDiscordStuff#171]
Check pls. i test he crash discord.

**Comment by Fishum** [comment]
I can confirm, discord crashes but betterdiscord does not auto-disable, meaning you can't use discord unless you remove this file from plugins

**Comment by PlayWolfYT** [comment]
Can confirm aswell. Had to go through all the plugins and manually delete them to find out its this one.

**Comment by vovklosev** [comment]
> Can confirm aswell. Had to go through all the plugins and manually delete them to find out its this one.

You can use the console to see which plugin crushes. I did so.

**Comment by steadyaero** [comment]
+1. Crashes when changing channels

**Comment by SunRaysFalls** [comment]
Can confirm too...

**Comment by nexioss** [comment]
for me too

**Comment by Traktool** [comment]
Can confirm too

To disable the plugin, you can do this :
Do "Windows + R", type %appdata%/BetterDiscord/data/stable
Open plugin.json and set "UnreadCountBadges" to false
Then save and relaunch Discord

Or this :
Do "Windows + R", type %appdata%/BetterDiscord/plugins
Delete "UnreadCountBadges.plugin.js"
Then save and relaunch Discord

**Comment by sapioit** [comment]
I can confirm, too! The fix above worked, for me. I found about it in an issue on BetterDiscord's Github page, issue which I made to suggest adding to BetterDiscord a way to make it easier for us to see which plugin or theme crashed BetterDiscord. Here's the link to that issue, in case you want to tell the devs you also want one of those possible solutions, so we don't have to manually search for which plugin crashed BetterDiscord.

https://github.com/BetterDiscord/BetterDiscord/issues/1260#issuecomment-1086628426

**Comment by Traktool** [comment]
I've just find a similar plugin that is working, here the link if some want : 
https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/UnreadBadgesRedux

I guess it's working, not perfect but worked

**Comment by sapioit** [comment]
Thank you very much for the alternative plugin!

**Comment by HypedDomi** [comment]
Strencher fixed the crashing. A few things might be still broken, but the main functionality is working. He uploaded a new Version on his Server in Support or you use this attachment link to the file https://cdn.discordapp.com/attachments/655486376858615838/958797518395822100/UnreadCountBadges.plugin.js

**Comment by sapioit** [comment]
Thanks for sharing! I'll try it after I wake up. I see the file shows the same version (`1.2.0`). He could have used something like `1.2.0a` or `1.2.001`, to make it more recent.

**Comment by Strencher** [comment]
Should be fixed in the latest version.
