### ISSUE TITLE
[PronounDB] Crash upon viewing user profile in popout

### ISSUE THREAD

**Issue by ubscal** [Strencher/BetterDiscordStuff#190]
When opening someones profile in a guild via the popout menu on the side, discord crashes.

**Comment by Saltssaumure** [comment]
Can confirm, clicking name in chat also crashes.

**Comment by Aura-Dacella** [comment]
Confirmed happens with me too

**Comment by HimitsuYami** [comment]
Happens here as well

**Comment by usesPython** [comment]
Looks like an issue with Discord breaking

https://github.com/Strencher/BetterDiscordStuff/blob/0224369ac5352bae35f3860e423c6bdafb7ebb27/PronounDB/PronounDB.plugin.js#L4989

which causes problems when it's used in

https://github.com/Strencher/BetterDiscordStuff/blob/0224369ac5352bae35f3860e423c6bdafb7ebb27/PronounDB/PronounDB.plugin.js#L5068-L5073

Workaround at the moment seems to be disabling User Popout in the PronounDB settings

**Comment by Daedalusspacegames** [comment]
![image](https://user-images.githubusercontent.com/26441263/167242385-a815f40b-c999-42fa-b621-a8c62b911dfd.png)

**Comment by TheChilliPL** [comment]
![image](https://user-images.githubusercontent.com/18823939/167260492-7c738be7-5de6-4600-bdde-7ee45bf983fa.png)

**Comment by Strencher** [comment]
Fixed in the latest version. Please update.
