### ISSUE TITLE
[UserDetails] Plugin is not working

### ISSUE THREAD

**Issue by zuzumi-f** [Strencher/BetterDiscordStuff#191]
The plugin only show an error icon
![Discord_hbaeYvHXrz](https://user-images.githubusercontent.com/79029257/166929409-5cab2ad5-8576-409c-81c9-e7411c25e6cf.png)
![Discord_umEp94Orhm](https://user-images.githubusercontent.com/79029257/166929796-39778e7f-6027-4387-8a94-368334eb9410.png)

[6/05/2022]
2.8.0 fix

**Comment by Debuggerz1** [comment]
1. Open up the source file using your favorite document editor

2. Using your editor's **search and replace** function 

3. Replace **"Header"** with **"LegacyHeader"**

**Comment by Technetium1** [comment]
Why close this issue @zuzumi-f?

**Comment by Strencher** [comment]
Because the issue has been fixed in the last update.

**Comment by Strencher** [comment]
Whoops, wrong button.
