### ISSUE TITLE
[ChannelDms] DM tab width is not in fixed width

### ISSUE THREAD

**Issue by reynoldyehezkiel** [Strencher/BetterDiscordStuff#193]
Members tab width is in fixed width, but DM tab doesn't. How to make DM tab width in fixed width?
There's two cases, with ClearVision theme and default theme.

With ClearVision v6.3.0 theme
![final_627595f404a70a00cc9e68e5_852475](https://user-images.githubusercontent.com/73789263/167220546-2251b4e0-0f89-4fdd-b8a4-7a57e23a1697.gif)

Default theme
![final_627598a9e4195f00702d46e4_671879](https://user-images.githubusercontent.com/73789263/167222666-74c1082e-a184-4ebe-9c9a-de1da324dc28.gif)

**Comment by Crystal-guy** [comment]
yeah, same for me, and there's any solution as i see

**Comment by reynoldyehezkiel** [comment]
I just found the solution if you are using ClearVision theme
add this code on your custom ClearVision theme css
```
.ChannelDms-channelmembers-wrap{
	width: 240px;
}
```
and i just checked discord default theme. it's seems the width is fixed
