### ISSUE TITLE
[ShowSessions] [BUG] Crash caused by modal

### ISSUE THREAD

**Issue by uptore** [Strencher/BetterDiscordStuff#194]
### Description:
When the sessions modal opens the client crashes. I'm not exactly sure why this has started happening. It could be that a ZeresPluginLibrary's update broke it or a Discord/BetterDiscord update broke it.

### Steps to reproduce:

1. Have BetterDiscord open with the latest versions of ShowSessions and ZeresPluginLibrary
2. Have ShowSessions configured to open a modal on session updates
3. Open another discord session (I've tested web and mobile)
4. Base Discord will crash (No BetterDiscord crashed popup)

### Console Error:
```
TypeError: Cannot read property 'Tags' of undefined
    at Modal (ShowSessions.plugin.js:850)
```

### Client Information:

> Stable 127135 (ed0fa2c)
> BetterDiscord 1.5.3
> Host 1.0.9004 Windows 10 64-Bit (10.0.19043)

**Comment by ccrowles** [comment]
I'm having the same issue since today.

Stable 127135 (ed0fa2c)
BetterDiscord 1.5.3
Host 1.0.9004 Windows 10 64-Bit (10.0.19044)

**Comment by Strencher** [comment]
Fixed in the latest version. Please update.
