### ISSUE TITLE
ChannelDM don't work

### ISSUE THREAD

**Issue by Crystal-guy** [Strencher/BetterDiscordStuff#197]
hey, i've installed channeldm plugin, but it do anything in discord... i dont know if i did a thing wrong, but i ask anyone for help.

**Comment by HypedDomi** [comment]
When you enable it, it should look like this in the Memberlist. Is there any error in the console?
![image](https://user-images.githubusercontent.com/50876016/168692093-c7f11969-0839-4b24-9dcc-cf999148510d.png)

**Comment by HypedDomi** [comment]
Closed due to inactivity
