### ISSUE TITLE
[UserBackgrounds] Unable to be launched

### ISSUE THREAD

**Issue by Rayjacker** [Strencher/BetterDiscordStuff#198]
When starting Discord, I get this window after plugins are loaded : 
![image](https://user-images.githubusercontent.com/77126320/168689083-6b79ae50-c03d-48f8-af34-5b9a54b3976a.png)
Clicking on the error crashes Discord immediately.
In the console, this error pops up : 
![image](https://user-images.githubusercontent.com/77126320/168689226-069cb322-960d-4b3b-bfd6-dab3366a17c9.png)

Using Stable 128373 (ef848a6)
BetterDiscord 1.5.3
Host 1.0.9004 
Windows 10 64-Bit (10.0.19044)

**Comment by HypedDomi** [comment]
Download the File again

**Comment by Rayjacker** [comment]
Did so, as soon as it finishes downloading the Addon Errors window pops up if Discord is running, Trying a reinstall while Discord is closed leads to the same issue.

**Comment by HypedDomi** [comment]
Can you show the content of the file and tell me from where youre downloading

**Comment by Rayjacker** [comment]
Wait, I'm an idiot that doesn't know how GitHub works. Downloading the file properly from https://github.com/Strencher/BetterDiscordStuff/tree/master/UserBackgrounds (and not the blob page that contains the file) gives these errors : 
![image](https://user-images.githubusercontent.com/77126320/168693817-3ef03dd1-5903-4474-87e6-72f703c00ff5.png)
![image](https://user-images.githubusercontent.com/77126320/168693882-9a3053bb-f678-48ad-8722-935d191c8720.png)

**Comment by HypedDomi** [comment]
Oh, my bad. I got confused by the META Error. Didn't realize I have the same error now

**Comment by Rayjacker** [comment]
Problem has been fixed as of 1.6.3.

**Comment by Rayjacker** [comment]
Aaaand it's happening again as of the latest Discord update. At least clicking on the error pop-up works now.

![Capture d’écran 2022-07-07 155943](https://user-images.githubusercontent.com/77126320/177977933-726df018-66b1-43f1-bfa5-8a7f4b0cb010.png)
![Capture d’écran 2022-07-07 155949](https://user-images.githubusercontent.com/77126320/177977961-e72eee2c-7307-40a2-816b-e2b89cdac675.png)

Stable 135402 (4c5bcd6)
BetterDiscord 1.5.3
Host 1.0.9005 Windows 10 64-Bit (10.0.19044)

**Comment by BigFlubba** [comment]
I am getting the same thing.

**Comment by HypedDomi** [comment]
UserBackgrounds isn't maintained any more
