### ISSUE TITLE
SpotifyLinks plugin not working for me

### ISSUE THREAD

**Issue by elhertz** [Strencher/BetterDiscordStuff#2]
Hey, i don't know how i found your plugin but I did.
When i click on a spotify link the spotify app will flash in the taskbar but it wont play the song, what's wrong?
thank you!

**Comment by Strencher** [comment]
yeah ik that the song does not play. I'll look into the plugin tomorrow. Thanks for the issue report!

**Comment by Strencher** [comment]
Sorry but it seems that Spotify does not allow autoplay.

**Comment by Strencher** [comment]
> When i click on a spotify link the spotify app will flash in the taskbar but it wont play the song,
it opens the song in Spotify and you can play it by clicking on the play button (in Spotify)

**Comment by elhertz** [comment]
Actually that's a lot better, thank you!

**Comment by Strencher** [comment]
no problem ;)
