### ISSUE TITLE
Crashes when typing ">:"

### ISSUE THREAD

**Issue by Jazun** [Strencher/BetterDiscordStuff#206]
When I enabled this plugin and then typed ">:" (e.g. >:( ) discord would crash. I went through every plugin I had and this one ended up being the problem.

**Comment by Strencher** [comment]
Which plugin exactly?

**Comment by HypedDomi** [comment]
Maybe ShowSessions with the slash command. Discord added Command Completion for a few extra prefixes

**Comment by Taithrah** [comment]
ShowSessions also causes a crash when typing . followed by a : or a capital or lowercase O E i S N

**Comment by re11ding** [comment]
Yes, I can confirm also that it's ShowSessions.

**Comment by JazunOwO** [comment]
Yes, showsessions, sorry, I thought I was opening an issue on a plugin and not a library of them

it won't allow me to comment normally so I'll just close with comment and hope it gets fixed

**Comment by HypedDomi** [comment]
Should be fixed. If not reopen this issue
