### ISSUE TITLE
[PlatformIndicators] Not compatible with compact mode

### ISSUE THREAD

**Issue by Vandesm14** [Strencher/BetterDiscordStuff#21]
When using PlatformIndicators with compact mode, this is the result:
![image](https://user-images.githubusercontent.com/23623276/113593598-99d76d80-9604-11eb-9be6-f42c2734abe5.png)

I have the "show next to username" option disabled, yet compact mode is still ruined. Please add compatibility for compact mode especially when the option to display indicators in the message list is turned off.

**Comment by Vandesm14** [comment]
Any updates on this?

**Comment by Strencher** [comment]
There's a beta in my server running, ask für the beta releases role and you can test it.

**Comment by Vandesm14** [comment]
Got the beta release, It's still broken on compact mode
![image](https://user-images.githubusercontent.com/23623276/116900856-3c384000-ac07-11eb-845e-9a4b8ef0d2f9.png)

**Comment by Strencher** [comment]
This issue has been solved in discord chat.
