### ISSUE TITLE
[PronounDB] Add pronouns context menu entry not appearing

### ISSUE THREAD

**Issue by nrgill28** [Strencher/BetterDiscordStuff#212]
Not sure if this is an issue on your end or with the library you use to add the context menu entry, but for the last couple weeks or so right clicking on a user no longer shows the option to add / change local pronouns. Otherwise the plugin still seems to work fine, displaying local pronouns previously set before the entry disappeared.

**Comment by HypedDomi** [comment]
Discord changed something in the User context menu again. iirc it should still show in DMs

**Comment by WeirdAlex03** [comment]
It used to show in DMs, but after the latest restarts, that doesn't work for me, either. I now have to manually open the config file and paste in the user id's for it.

Steps for anyone looking to add/change pronouns while the context menu option isn't available:
1. Enable developer mode
   1. Go to User Settings
   2. Open the Advanced tab and turn on "Developer Mode"
2. Copy the targetted user's id
   * Right click their __name__ above a message and click "Copy ID"
   * **OR** right click their name in the member list and click "Copy ID"
   * **OR** open their profile, open the 3-dot menu next the Friend Request button, and click "Copy ID"
3. Open the plugin's config file
   1. Go to User Settings
   2. Open the Plugins tab
   3. Click "Open Plugins Folder" at the top of the page
   4. Scroll down until you find `PronounDB.config.json`
   5. Double click the file to open it (or right click > Open with > select your preferred text or code editor)
4. Scroll down to the bottom
5. Add the new pronoun(s)
   1. Find the last line with the format `"123456789012345678": "xx"` (it shouldn't have a `,` comma at the end)
   2. Add a comma to the end of that line
   3. Add a new line and add spaces to line up with the previous lines
   4. Following the format of the previous lines:
      * Paste in the user id you copied, surrounded in `"` double quotes
      * Add a `:` colon and ` ` space
      * Add the pronoun short identifier (or anything for a custom pronoun), again surrounded in `"` double quotes
        * Not sure what the short identifier is? Find it at https://pronoundb.org/docs
      * If you are adding more pronouns, add a `,` comma to the end of this line and repeat
      * Make sure the last line does **not** have a `,` comma at the end
6. Save the file
7. Restart Discord
   * If Discord stays open in the background, find the icon in the system tray (bottom right of the task bar, might be in `^` overflow menu), then right click and select "Quit Discord"
   * When you reopen Discord, you should see the new pronoun(s)

**Comment by embyveddii** [comment]
how is this still not fixed
