### ISSUE TITLE
Component Error

### ISSUE THREAD

**Issue by Kuzambee01** [Strencher/BetterDiscordStuff#216]
None of the DMS show when I restart my discord or turn off and turn on the plugin

**Comment by fiftysdeath** [comment]
![image](https://user-images.githubusercontent.com/101597730/179362392-949cf953-9856-43e5-9064-23329a8e677d.png)

yeah currently having this issue as well, ive tried turning off all plugins (besides library ones) and having only this one enabled and it doesnt work no matter what i try. hopefully this gets fixed soon because i use this feature a lot when monitoring chat in servers

**Comment by Mina-1316** [comment]
![image](https://user-images.githubusercontent.com/74696602/179372985-49242ef3-c46e-425d-bc80-96bc91f714bb.png)

When clicking sidebar DM, TypeError thrown so maybe this can be problem?

**Comment by Strencher** [comment]
Yeah. Thanks for the additional error logs. I'll take a look into it tomorrow.

**Comment by ShauwThen** [comment]
up :)

**Comment by fiftysdeath** [comment]
![image](https://user-images.githubusercontent.com/101597730/179563719-cdff2ea0-32ce-411f-9cb4-d606f576a9e0.png)
yeah still broken for me :| checked for updates, uninstalled and reinstalled, nada


> up :)

**Comment by fiftysdeath** [comment]
![image](https://user-images.githubusercontent.com/101597730/180629791-6c47b827-8377-47ec-bfce-3dff821efeea.png)
![image](https://user-images.githubusercontent.com/101597730/180629804-38ef9eae-3781-4988-b894-e00e217a0072.png)

(on Linux this time with BD installed) but having this error again... I'll let everybody know if it's doing the same thing on Windows here soon

**Comment by fiftysdeath** [comment]
just logged into my Windows system (been busy with other things) and yeah its still broken only when you click on a user to open the DM 
![image](https://user-images.githubusercontent.com/101597730/180838356-e609bed0-54ea-4334-9bd9-f29452be97bb.png)

**Comment by ShauwThen** [comment]
fixed for me
![Sans titre-1](https://user-images.githubusercontent.com/20680890/180839475-a3cbd4c7-ca0b-46fa-9f44-38ccbc257711.png)

**Comment by maenDisease** [comment]
> ### **[ShauwThen](/ShauwThen) ** commented [2 hours ago](#issuecomment-1194395498)

Click on one of your Direct Messages

**Comment by HypedDomi** [comment]
Fixed. Redownload from GitHub
