### ISSUE TITLE
[PlatformIndicators] Crash with 'Show in MemberList' option in a server

### ISSUE THREAD

**Issue by Fadexz** [Strencher/BetterDiscordStuff#223]
I'm not sure what the cause is but when this option ('Show in MemberList') is enabled my Discord client will crash when I visit a specific one of my servers but has only been occurring very recently and has never happened before.

If there is anything like a log I can show just let me know.

**Comment by HypedDomi** [comment]
You could check the Console (`CTRL` + `SHIFT` + `I`) and send the Errors then here

**Comment by Fadexz** [comment]
Appreciate it
I decided to test the feature again and it seems to work fine so it could have been something in the server at the time causing it but also there have been updates that have made changes so I don't know if that would affect anything.

**Comment by Fadexz** [comment]
Just had this issue happen again on another server this time.

Hopefully this console log helps

`
775bb81aae8c95480f4e.js:130 [Routing/Utils] transitionTo - Transitioning to /channels/832268474066665512/838822704605823026
775bb81aae8c95480f4e.js:130 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nl (0fff6a729a4eb23485c7.js:6129)
    at e (0fff6a729a4eb23485c7.js:6068)
    at Bo (0fff6a729a4eb23485c7.js:6080)
    at $s (0fff6a729a4eb23485c7.js:6125)
    at Gu (0fff6a729a4eb23485c7.js:6115)
    at wu (0fff6a729a4eb23485c7.js:6115)
    at Uu (0fff6a729a4eb23485c7.js:6115)
    at Au (0fff6a729a4eb23485c7.js:6112)
    at 0fff6a729a4eb23485c7.js:6057
    at t.unstable_runWithPriority (0fff6a729a4eb23485c7.js:6246)
    at Ki (0fff6a729a4eb23485c7.js:6057)
    at qi (0fff6a729a4eb23485c7.js:6057)
    at Xi (0fff6a729a4eb23485c7.js:6057)
    at 0fff6a729a4eb23485c7.js:6134
    at we (0fff6a729a4eb23485c7.js:6134)
    at Ve (0fff6a729a4eb23485c7.js:6025)
    at 0fff6a729a4eb23485c7.js:6048
    at Vr (0fff6a729a4eb23485c7.js:6048)
    at rn (0fff6a729a4eb23485c7.js:6035)
    at nn (0fff6a729a4eb23485c7.js:6035)
    at t.unstable_runWithPriority (0fff6a729a4eb23485c7.js:6246)
    at Ki (0fff6a729a4eb23485c7.js:6057)
    at Ue (0fff6a729a4eb23485c7.js:6134)
    at en (0fff6a729a4eb23485c7.js:6034)
    at HTMLDivElement.r (775bb81aae8c95480f4e.js:126)
(anonymous) @ 775bb81aae8c95480f4e.js:130
t.<computed> @ 0fff6a729a4eb23485c7.js:4433
Es @ 0fff6a729a4eb23485c7.js:6100
Is.a.componentDidCatch.n.callback @ 0fff6a729a4eb23485c7.js:6100
pa @ 0fff6a729a4eb23485c7.js:6060
gs @ 0fff6a729a4eb23485c7.js:6102
Bu @ 0fff6a729a4eb23485c7.js:6120
t.unstable_runWithPriority @ 0fff6a729a4eb23485c7.js:6246
Ki @ 0fff6a729a4eb23485c7.js:6057
Vu @ 0fff6a729a4eb23485c7.js:6116
Au @ 0fff6a729a4eb23485c7.js:6112
(anonymous) @ 0fff6a729a4eb23485c7.js:6057
t.unstable_runWithPriority @ 0fff6a729a4eb23485c7.js:6246
Ki @ 0fff6a729a4eb23485c7.js:6057
qi @ 0fff6a729a4eb23485c7.js:6057
Xi @ 0fff6a729a4eb23485c7.js:6057
(anonymous) @ 0fff6a729a4eb23485c7.js:6134
we @ 0fff6a729a4eb23485c7.js:6134
Ve @ 0fff6a729a4eb23485c7.js:6025
(anonymous) @ 0fff6a729a4eb23485c7.js:6048
Vr @ 0fff6a729a4eb23485c7.js:6048
rn @ 0fff6a729a4eb23485c7.js:6035
nn @ 0fff6a729a4eb23485c7.js:6035
t.unstable_runWithPriority @ 0fff6a729a4eb23485c7.js:6246
Ki @ 0fff6a729a4eb23485c7.js:6057
Ue @ 0fff6a729a4eb23485c7.js:6134
en @ 0fff6a729a4eb23485c7.js:6034
r @ 775bb81aae8c95480f4e.js:126
`

**Comment by HypedDomi** [comment]
React Error Code:
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

**Comment by HypedDomi** [comment]
Fixed in [6a452fb](https://github.com/Strencher/BetterDiscordStuff/commit/6a452fb4e33c0d1da8d63d457c8ae7d22420902a)
