### ISSUE TITLE
[UserDetails] Plugin is not working

### ISSUE THREAD

**Issue by TazLaud** [Strencher/BetterDiscordStuff#225]
Tried reinstalling BetterDiscord and only enabling the plugin but still getting the message.

![image](https://user-images.githubusercontent.com/23557192/182259840-b8cb10d2-bd20-42fc-8de8-f91a0a25f4e1.png)

**Comment by HypedDomi** [comment]
Its known. Discord broke many Plugins with the last update

**Comment by HayWeeMe** [comment]
Edit the plugin itself and remove "ActionTypes." in the code at the lines 983, 986 and 1368 (basically all 3 ActionTypes.) and update the plugin version to something like 2.9.1 to stop BD from updating it.

I tired requesting a commit to fix the plugin but I was recommended to not do it in the master branch but in the dev branch but I couldn't really figure out how to translate those changes to the dev branch.

**Comment by HypedDomi** [comment]
@HayWeeMe I'll fix it, and then you can see how we meant it

**Comment by HypedDomi** [comment]
Fixed. Redownload from GitHub

**Comment by TazLaud** [comment]
> Fixed. Redownload from GitHub

Working perfectly, thanks !
