### ISSUE TITLE
[BUG] - PlatformIndicators Could Not Be Constructed (Ptb 139684 (95340d3))

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Strencher/BetterDiscordStuff#233]
```text
Ptb 139684 (95340d3)
BetterDiscord 1.5.3-Hotfix2
Host 0.0.63 OS X 10.15.7 (20.6.0)
```

This is also happening on Canary
<img width="701" alt="PlatformIndicators" src="https://user-images.githubusercontent.com/2242880/182522964-e7eb8bbc-20be-4e05-a41c-dbd2b1ee13e2.png">

Console Log:
[console_Platfromindicators.log](https://github.com/Strencher/BetterDiscordStuff/files/9247918/console_Platfromindicators.log)

**Comment by Masono03** [comment]
same on canary.

Canary 139699 (bdc9502)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by XxUnkn0wnxX** [comment]
Working everywhere as of 08e3121122a313151b76f22e0783f85205b82f3c
