### ISSUE TITLE
[BUG] - ChannelDms Could Not Be Constructed (Ptb 139684 (95340d3)) | Stable 139777 (21b018b)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Strencher/BetterDiscordStuff#235]
```text
Ptb 139684 (95340d3)
BetterDiscord 1.5.3-Hotfix2
Host 0.0.63 OS X 10.15.7 (20.6.0)
```

This is also happening on Canary
<img width="703" alt="ChannelDMs" src="https://user-images.githubusercontent.com/2242880/182523150-f31bd9de-846c-4287-9631-90b3763a8659.png">

Console Log:
[console_channeldms.log](https://github.com/Strencher/BetterDiscordStuff/files/9247923/console_channeldms.log)

**Comment by Masono03** [comment]
same on canary.
Canary 139699 (bdc9502)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by XxUnkn0wnxX** [comment]
Now happening on Stable to
```text
Stable 139777 (21b018b)
BetterDiscord 1.5.3-Hotfix2
Host 0.0.267 OS X 10.15.7 (20.6.0)
```
<img width="1670" alt="Screen Shot 2022-08-04 at 7 14 37 am" src="https://user-images.githubusercontent.com/2242880/182713806-1eebb62a-d3dc-4e6d-9395-7f4e168161f5.png">

**Comment by HypedDomi** [comment]
Fixed. Redownload from GitHub
