### ISSUE TITLE
[BUG] - InvisibleTyping Could Not Be Constructed (Ptb 139684 (95340d3))

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Strencher/BetterDiscordStuff#236]
```text
Ptb 139684 (95340d3)
BetterDiscord 1.5.3-Hotfix2
Host 0.0.63 OS X 10.15.7 (20.6.0)
```

This is also happening on Canary
<img width="684" alt="InvisibleTyping" src="https://user-images.githubusercontent.com/2242880/182523229-60ad97fd-4779-4781-b4ce-7f6b410783a3.png">

Console Log:
[console_invisibletyping.log](https://github.com/Strencher/BetterDiscordStuff/files/9247926/console_invisibletyping.log)

**Comment by Masono03** [comment]
same on canary.
Canary 139699 (bdc9502)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by XxUnkn0wnxX** [comment]
Working everywhere as of 32bd29f8e9a1f02d2310f59853f8e84b92324bda
