### ISSUE TITLE
[BUG] - ShowSessions Could Not Be Constructed (Ptb 139684 (95340d3)) | Stable 139777 (21b018b)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Strencher/BetterDiscordStuff#237]
```text
Ptb 139684 (95340d3)
BetterDiscord 1.5.3-Hotfix2
Host 0.0.63 OS X 10.15.7 (20.6.0)
```

This is also happening on Canary
<img width="713" alt="Showsessions" src="https://user-images.githubusercontent.com/2242880/182523272-b001aa31-68eb-4c5a-996c-e44d11f66f26.png">

Console Log:
[console_showsessions.log](https://github.com/Strencher/BetterDiscordStuff/files/9247927/console_showsessions.log)

**Comment by Masono03** [comment]
same on canary. 
Canary 139699 (bdc9502)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by zachariapopcorn** [comment]
Same on stable
BetterDiscord 1.5.3-hotfix2
Windows 10

**Comment by XxUnkn0wnxX** [comment]
Now happening on Stable to
```text
Stable 139777 (21b018b)
BetterDiscord 1.5.3-Hotfix2
Host 0.0.267 OS X 10.15.7 (20.6.0)
```
<img width="1670" alt="Screen Shot 2022-08-04 at 7 14 37 am" src="https://user-images.githubusercontent.com/2242880/182713726-3760c82e-80ca-49f5-aefa-71f4e767e8c5.png">

**Comment by muluffel** [comment]
Same on 
Stable 140355 (cd30e81)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.9005 Windows 10 64-Bit (10.0.22622) --> Actually Win11 64 Bit Insider Beta Channel
![image](https://user-images.githubusercontent.com/65601356/183284949-9af6582f-37a3-480c-bd4b-4a84fa933b21.png)

**Comment by HypedDomi** [comment]
Fixed. Redownload from GitHub
