### ISSUE TITLE
ShowAllActivities cant be constructed on newest updates

### ISSUE THREAD

**Issue by Masono03** [Strencher/BetterDiscordStuff#241]
As many other plugins now died on the new updates of discord. Cant be constructed. 

Canary 139699 (bdc9502)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by patrickzhou1234** [comment]
Same here 
![image](https://i.imgur.com/VPd00a5.png)

**Comment by BlueStarBRS** [comment]
same here:

```
ShowAllActivities: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:306851)
    at Object.loadAddon (<anonymous>:4:268341)
    at Object.loadAddon (<anonymous>:4:305889)
    at Object.reloadAddon (<anonymous>:4:269050)
    at FSWatcher.<anonymous> (<anonymous>:4:266224)
```

**Comment by Kalaborative** [comment]
@Masono03 @BlueStarBRS Replace it with this one I updated it myself: https://gist.github.com/Kalaborative/32c85b4a79144ea895e9c4ae79c7a987

Works fine for me now.

**Comment by Technetium1** [comment]
@Kalaborative pelase provide a diff. Saying "use this one I did myself" is a bit suspiscious. If you fixed it why not do a pull request?

**Comment by Reagy** [comment]
> @Kalaborative pelase provide a diff. Saying "use this one I did myself" is a bit suspiscious. If you fixed it why not do a pull request?

Had a check through their code and they've only changed two lines, 158 and 166 with the following...

158 `return ___createMemoize___(this, 'Text', () => BdApi.findModuleByDisplayName('LegacyText'))`
166 `return ___createMemoize___(this, 'Dispatcher', () => BdApi.findModuleByProps('dispatch', 'isDispatching'))`

Still this should be a pull request, not a "hey I fixed it use this lol"

**Comment by Kalaborative** [comment]
My apologies if you interpreted that way. It was a minimal workaround which is why I opted for this option rather than a PR.

**Comment by BlueStarBRS** [comment]
> @Masono03 @BlueStarBRS Replace it with this one I updated it myself: https://gist.github.com/Kalaborative/32c85b4a79144ea895e9c4ae79c7a987
> 
> Works fine for me now.

 thank you very very mush <3

**Comment by BlueStarBRS** [comment]
is there a way that again some auto patcher can fix some problems like the last big big base update ?
bacuase one of my favorite plugins 8channelDms) is still brocken :/

**Comment by HypedDomi** [comment]
Fixed. Redownload from GitHub
