### ISSUE TITLE
BetterBannedUsers - Could not be constructed

### ISSUE THREAD

**Issue by Pokesketch** [Strencher/BetterDiscordStuff#244]
It seems that BetterBanned Users isn't working as well.
![image](https://user-images.githubusercontent.com/62312740/182669799-9f24d43a-4042-4488-b34f-4cf0750c3963.png)

**Comment by XxUnkn0wnxX** [comment]
I can't reproduce this, BetterBannedUsers v1.2.3 loads for me on
every client Stable, Canary, PTB
```text
Stable 139777 (21b018b)
BetterDiscord 1.5.3-Hotfix2
Host 0.0.267 OS X 10.15.7 (20.6.0)

<img width="599" alt="Screen Shot 2022-08-04 at 7 40 52 am" src="https://user-images.githubusercontent.com/2242880/182717548-08b981f3-7d51-4afa-8fe5-6ce52bce0ec2.png">

**Comment by HypedDomi** [comment]
Fixed. Redownload from GitHub
