### ISSUE TITLE
InvisibleTyping - Could not be constructed 

### ISSUE THREAD

**Issue by Pokesketch** [Strencher/BetterDiscordStuff#245]
![image](https://user-images.githubusercontent.com/62312740/182670175-43a63619-3e78-4088-9ea5-5b75e7792fe7.png)

**Comment by STaRDoGGCHaMP** [comment]
Same for me

**Comment by emmaexe** [comment]
I also get this error.

> InvisibleTyping: Could not be constructed.
      at Object.initializeAddon (<anonymous>:4:306851)
      at Object.loadAddon (<anonymous>:4:268341)
      at Object.loadAddon (<anonymous>:4:305889)
      at Object.loadAllAddons (<anonymous>:4:270617)
      at Object.initialize (<anonymous>:4:265066)
      at Object.initialize (<anonymous>:4:305099)
      at Object.startup (<anonymous>:4:367116)

**Comment by Taupe** [comment]
same for me

```
InvisibleTyping: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:306851)
    at Object.loadAddon (<anonymous>:4:268341)
    at Object.loadAddon (<anonymous>:4:305889)
    at Object.loadAllAddons (<anonymous>:4:270617)
    at Object.initialize (<anonymous>:4:265066)
    at Object.initialize (<anonymous>:4:305099)
    at Object.startup (<anonymous>:4:367116)
```

**Comment by AnaIytics** [comment]
Same here, happened with platformindicators aswell

**Comment by patrickzhou1234** [comment]
Same Here
![image](https://i.imgur.com/VPd00a5.png)

**Comment by allys7** [comment]
I am getting the same error overall, but a slightly different trace so I figured I would put it in here

```
InvisibleTyping: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:306851)
    at Object.loadAddon (<anonymous>:4:268341)
    at Object.loadAddon (<anonymous>:4:305889)
    at FSWatcher.<anonymous> (<anonymous>:4:266190)
```

**Comment by TTVAdolfHitler** [comment]
> ![image](https://user-images.githubusercontent.com/62312740/182670175-43a63619-3e78-4088-9ea5-5b75e7792fe7.png)

same

**Comment by XxUnkn0wnxX** [comment]
I can't reproduce this, invisible typing v1.2.2 loads for me on
every client Stable, Canary, PTB
```text
Stable 139777 (21b018b)
BetterDiscord 1.5.3-Hotfix2
Host 0.0.267 OS X 10.15.7 (20.6.0)
```
<img width="605" alt="Screen Shot 2022-08-04 at 7 29 52 am" src="https://user-images.githubusercontent.com/2242880/182715697-759db414-336c-42cc-afcd-5acd4d617bb8.png">

**Comment by MrDerpi** [comment]
Same issue here

`InvisibleTyping:` Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:306851)
    at Object.loadAddon (<anonymous>:4:268341)
    at Object.loadAddon (<anonymous>:4:305889)
    at Object.loadAllAddons (<anonymous>:4:270617)
    at Object.initialize (<anonymous>:4:265066)
    at Object.initialize (<anonymous>:4:305099)
    at Object.startup (<anonymous>:4:367116)``

**Comment by Jnss98b** [comment]
> Can reproduce on v1.2.1, but can't on 1.2.2 (issue resolved), users have to update to 1.2.2 via newest branch, since current one on betterdiscord website is outdated by two versions.

Don't plugins and themes pull directly from their respective repos so that's not really a problem anyway?

**Comment by Moa4sh** [comment]
> > Can reproduce on v1.2.1, but can't on 1.2.2 (issue resolved), users have to update to 1.2.2 via newest branch, since current one on betterdiscord website is outdated by two versions.
> 
> Don't plugins and themes pull directly from their respective repos so that's not really a problem anyway?

Can confirm, downloading 1.2.2 manually from the file repository and placing it in the Discord plugins folder did the trick. And no, for some reason the latest version isn't being pushed automatically. Perhaps Strencher hasn't pushed the update yet for some reason. 

For those trying to manually update and aren't familiar with GitHub (like me), here are instructions on how to download the file: https://www.wikihow.com/Download-a-File-from-GitHub

**Comment by Jnss98b** [comment]
>And no, for some reason the latest version isn't being pushed automatically. Perhaps Strencher hasn't pushed the update yet for some

Nope there's no pushing needed. The way BD plugins are set up, they automatically reflect the source as pushed on github upon loading. I found out why tho. The plugin crashes before it can prompt the user to update and thus requires a manual update

**Comment by Moa4sh** [comment]
> Nope there's no pushing needed. The way BD plugins are set up, they automatically reflect the source as pushed on github upon loading. I found out why tho. The plugin crashes before it can prompt the user to update and thus requires a manual update

Ah, makes sense.

**Comment by ItsdMeSoFYou** [comment]
Same here

**Comment by maenDisease** [comment]
> > And no, for some reason the latest version isn't being pushed automatically. Perhaps Strencher hasn't pushed the update yet for some
> 
> Nope there's no pushing needed. The way BD plugins are set up, they automatically reflect the source as pushed on github upon loading. I found out why tho. The plugin crashes before it can prompt the user to update and thus requires a manual update

There's no update prompt because the Zlib updater can't read the plugin, as the broken plugin itself can't construct/compile.

**Comment by muluffel** [comment]
Same on 
Stable 140355 (cd30e81)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.9005 Windows 10 64-Bit (10.0.22622) --> Actually Win11 64 Bit Insider Beta Channel
![image](https://user-images.githubusercontent.com/65601356/183284949-9af6582f-37a3-480c-bd4b-4a84fa933b21.png)

**Comment by HypedDomi** [comment]
Fixed. Redownload from GitHub
