### ISSUE TITLE
MemberCount - Could not be constructed

### ISSUE THREAD

**Issue by HmmSad** [Strencher/BetterDiscordStuff#247]
This has broken due to the new discord update
Errors: 
<html>
<body>

1 | MemberCount: Could not be constructed.
-- | --
2 | at Object.initializeAddon (<anonymous>:4:306851)
3 | at Object.loadAddon (<anonymous>:4:268341)
4 | at Object.loadAddon (<anonymous>:4:305889)
5 | at Object.loadAllAddons (<anonymous>:4:270617)
6 | at Object.initialize (<anonymous>:4:265066)
7 | at Object.initialize (<anonymous>:4:305099)
8 | at Object.startup (<anonymous>:4:367116)

</body>
</html>

**Comment by HypedDomi** [comment]
MemberCount is discontinued. But probably needs to be rebuild. If you have a bit of Node Knowledge, you could try to build it yourself with BdBuilder
