### ISSUE TITLE
ShowSessions - Could not be constructed

### ISSUE THREAD

**Issue by cabbagefork** [Strencher/BetterDiscordStuff#248]
![image](https://user-images.githubusercontent.com/31359599/182837565-7cca6791-dd78-490d-a9a8-c82285935f38.png)

Just like most plugins that broke due to the most recent Discord update, this one is also facing issues.

Stable 139968 (2d0a68b)
BetterDiscord 1.5.3-Hotfix2
Windows 10 64-Bit (10.0.19044)

**Comment by HypedDomi** [comment]
Fixed. Redownload from GitHub
