### ISSUE TITLE
StatusEverywhere - Yeah, broken too

### ISSUE THREAD

**Issue by M0REKZ** [Strencher/BetterDiscordStuff#249]
<img width="638" alt="Captura de Pantalla 2022-08-04 a la(s) 11 12 04" src="https://user-images.githubusercontent.com/60852359/182883118-d32739c5-82be-4b54-98b1-965081feebc6.png">

**Comment by softieeeeee** [comment]
same story here

**Comment by M0REKZ** [comment]
it looks like is working now, so, closing
