### ISSUE TITLE
ShowSettions Could not be constructed

### ISSUE THREAD

**Issue by IXSENPA1XI** [Strencher/BetterDiscordStuff#250]
ShowSessions: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:306851)
    at Object.loadAddon (<anonymous>:4:268341)
    at Object.loadAddon (<anonymous>:4:305889)
    at Object.loadAllAddons (<anonymous>:4:270617)
    at Object.initialize (<anonymous>:4:265066)
    at Object.initialize (<anonymous>:4:305099)
    at Object.startup (<anonymous>:4:367116)

**Comment by HypedDomi** [comment]
Download the latest version from github

**Comment by XxUnkn0wnxX** [comment]
ShowSessions 1.3.2 is still the broken one btw, it hasn't been updated for over a month.

**Comment by Craftzman7** [comment]
Is there a workaround available for this?

**Comment by DaniNissan** [comment]
ShowSessions got fixed but not uploaded on the Repo yet. You can get the updated fix here: https://cdn.discordapp.com/attachments/655486376858615838/1004397458958336000/ShowSessions.plugin.js

**Comment by jogerj** [comment]
> ShowSessions got fixed but not uploaded on the Repo yet. You can get the updated fix here: https://cdn.discordapp.com/attachments/655486376858615838/1004397458958336000/ShowSessions.plugin.js

Fix loads correctly but version number needs to be updated

**Comment by HypedDomi** [comment]
Construction Error fixed. Redownload from GitHub
