### ISSUE TITLE
[BUG] Plugin: InvisibleTyping does not work on BetterDiscord 1.5.3-Hotfix2

### ISSUE THREAD

**Issue by PtrckM** [Strencher/BetterDiscordStuff#254]
The plugin [InvisibleTyping.plugin.js](https://github.com/Strencher/BetterDiscordStuff/blob/06e4ec4ef7c38d0d001d240d7cc42b18ae2cf242/InvisibleTyping/InvisibleTyping.plugin.js)  does not work on version `BetterDiscord 1.5.3-Hotfix2`

![image](https://user-images.githubusercontent.com/54516858/183237404-bc84f184-9d7a-45d0-9d65-00f73f40dcfd.png)

Re-download does not help as well.

**Comment by Bagny89** [comment]
![image](https://user-images.githubusercontent.com/33706352/183239854-d8b05ae6-7f79-45dd-89ad-a1725bce3e42.png)
Yes, I confirm. I too am not loaded and this error appears.

**Comment by remotemachine1** [comment]
please fix muah

**Comment by ArjhanToteck** [comment]
I am having the same issue.

**Comment by dualznz** [comment]
same

**Comment by xchatiii** [comment]
Duplicate of #245

**Fixed, by the way.**
https://github.com/Strencher/BetterDiscordStuff/issues/245#issuecomment-1204649617

pls close

**Comment by PtrckM** [comment]
fix download latest version of [InvisibleTyping](https://betterdiscord.app/Download?id=295)
