### ISSUE TITLE
[StatusEverywhere] - No longer working

### ISSUE THREAD

**Issue by zany130** [Strencher/BetterDiscordStuff#268]
![image](https://user-images.githubusercontent.com/25832539/184017092-af0c28d3-19cb-430c-a465-db121e89e70f.png)

**Comment by Segergren** [comment]
Same issue.

**Comment by BlackusPL** [comment]
Platform Indicators doesn't work too

**Comment by HypedDomi** [comment]
They are all fixed. I suggest you to join [Strenchers Support Server](https://discord.gg/gvA2ree) or download them from GitHub again

**Comment by zany130** [comment]
![image](https://user-images.githubusercontent.com/25832539/184436180-63544120-43ab-4098-8b6c-a4d7de90b6f5.png)

**Comment by zany130** [comment]
just found https://github.com/Strencher/BetterDiscordStuff/issues/243 so i guess this bug can be closed as StatusEverywhere is now working
