### ISSUE TITLE
[PronounDB] Shown twice on profile

### ISSUE THREAD

**Issue by asportnoy** [Strencher/BetterDiscordStuff#27]
v0.0.3 of PronounDB shows the pronoun twice on the person's profile
![image](https://user-images.githubusercontent.com/14863373/120023291-34c04880-bfb3-11eb-911b-ca0b02748a65.png)

**Comment by Strencher** [comment]
Thanks for the report, i'll look into it.

**Comment by MinekPo1** [comment]
Does not happen to me. I believe v0.0.3 shouldn't be the fault, as the code for the injection was not modified.

**Comment by Strencher** [comment]
I had that error too a while ago, a client reload fixed it.

**Comment by asportnoy** [comment]
Weird, I just reloaded Discord and it fixed itself. Wonder if it was due to the update making it inject twice.

**Comment by MinekPo1** [comment]
I was gonna recommend doing that, but though nahh.

**Comment by Strencher** [comment]
probably.

**Comment by asportnoy** [comment]
While I'm here it would be nice to have a dropdown for choosing local pronouns.

**Comment by MinekPo1** [comment]
Again I have not changed the inject code.
