### ISSUE TITLE
Plugin had no exports or @name property

### ISSUE THREAD

**Issue by jeanmichelmorin** [Strencher/BetterDiscordStuff#272]
Error loading plugin v1.2.2:

Plugin had no exports or @name property

**Comment by HypedDomi** [comment]
Which Plugin is this?

**Comment by jeanmichelmorin** [comment]
@HypedDomi 

ChannelDms
https://github.com/Strencher/BetterDiscordStuff/tree/master/ChannelDms

**Comment by adsdawdfawdcwacdaw** [comment]
I'm getting the same issue with

MemberCount
TypingUsersPlus
Userbackgrounds

**Comment by 13c37** [comment]
same

**Comment by Torential** [comment]
Also getting this with **InvisibleTyping** and **UserDetails**

**Comment by HypedDomi** [comment]
Cant reproduce for the following Plugins:
- InvisibleTyping
- UserDetails
- ShowAllActivities

MemberCount and UserBackgrounds aren't maintained any more. ChannelDMs got fixed, redownload it from GitHub

**Comment by HypedDomi** [comment]
I triggered the rebuild of TypingUsersPlus. When any new Errors occur, reopen this issue
