### ISSUE TITLE
[BUG] ChannelDMS plgin had no exports or @name property

### ISSUE THREAD

**Issue by BlueStarBRS** [Strencher/BetterDiscordStuff#273]
i cant use the plugin BDiscord error output: 
![image](https://user-images.githubusercontent.com/25110093/184697363-3f453356-94ad-4edf-b077-b4522cac7e6a.png)
pls thx

**Comment by HypedDomi** [comment]
Redownload from GitHub

**Comment by BlueStarBRS** [comment]
> Redownload from GitHub
Danke

"THX"
