### ISSUE TITLE
[ShowAllActivities] Plugin could not be compiled

### ISSUE THREAD

**Issue by MaksiWWGaming** [Strencher/BetterDiscordStuff#275]
![image](https://user-images.githubusercontent.com/73423265/185148934-20acc40b-cab8-4b8e-8ef9-0bc38151d685.png)

Using the latest version of BetterDiscord and DiscordPTB on Windows11

**Comment by MonliH** [comment]
I'm also having this issue on Linux, using the latest version of BetterDiscord.

**Comment by HypedDomi** [comment]
Can you both try the latest Version from GitHub

**Comment by vincentwang0905** [comment]
same
![image](https://user-images.githubusercontent.com/76867533/185748506-5f1d5dab-44c0-47f9-9146-6b40c807f5c6.png)

**Comment by HypedDomi** [comment]
Cant replicate with the latest Version of both Plugins. Try redownloading from GitHub and reopen this issue when you still have this issue
