### ISSUE TITLE
Plugins not working 

### ISSUE THREAD

**Issue by Nirgranth** [Strencher/BetterDiscordStuff#276]
ChannelDms

![image](https://user-images.githubusercontent.com/48947296/185152385-7a4f1988-972d-4f56-895b-8be613397e79.png)

**Comment by maenDisease** [comment]
AvatarsEverywhere isn't even by Strencher

**Comment by maenDisease** [comment]
Most if not all of the plugins here can be fixed by either redownloading from the BD site or on the repo

**Comment by Nirgranth** [comment]
My bad  Channeldms still has the issue

**Comment by maenDisease** [comment]
channeldms is already fixed, redownload from the repo
