### ISSUE TITLE
[LinkChannels] Red Icon on every Channel

### ISSUE THREAD

**Issue by Soulivan71** [Strencher/BetterDiscordStuff#281]
Ptb 143659 (09bf559)
BetterDiscord 1.6.3
Host 1.0.1017

**Comment by HypedDomi** [comment]
Known. Use this Version until ZeresLib Module is fixed:
[Fixed LinkChannels Version](https://cdn.discordapp.com/attachments/655486376858615838/1007554045059289138/LinkChannels.plugin.js)

**Comment by Soulivan71** [comment]
Thx !
