### ISSUE TITLE
[StatusEverywhere] Compatibility for themes with custom avatar border radius

### ISSUE THREAD

**Issue by N-NNoThing** [Strencher/BetterDiscordStuff#284]
The plugin rounds up the avatars profiles pictures on themes that are squared, here is a screen capture with plugin enabled:
![image](https://user-images.githubusercontent.com/58456664/189102219-b20605ad-dbd7-43b1-b7cf-86cb1a7e69a9.png)

And disabled:
![image](https://user-images.githubusercontent.com/58456664/189103310-0fa40228-15db-4322-ac88-4162da791018.png)

I was trying to fix it with this custom CSS but im not an CSS expert and it doesn't work
![image](https://user-images.githubusercontent.com/58456664/189104309-36c2aa57-409a-4312-b1b5-65241590405f.png)

The theme is a modified version of:
https://betterdiscord.app/theme/Cyberpunk%202077

**Comment by HypedDomi** [comment]
The Avatar has a Mask. Use this CSS:
```css
.StatusEverywhere-avatar-chatAvatar > svg > foreignObject {
    mask: unset
}
```

**Comment by HypedDomi** [comment]
@N-NNoThing Can I close this issue?
