### ISSUE TITLE
[channel dms] doesn't work for me for some reason

### ISSUE THREAD

**Issue by SamanthaWamtha** [Strencher/BetterDiscordStuff#285]
i might be doing something wrong but channel dms just doesn't work for me at all. is it supposed to have a nother button to open it? if i press message after right clicking on someone it just goes to a dms page

**Comment by HypedDomi** [comment]
You have in the Memberlist on top a Tabbar with 2 Tabs. one for the Servermembers and one for your DMs
<img width="241" alt="image" src="https://user-images.githubusercontent.com/50876016/189305262-cef37e1c-f01a-496d-ba23-f3ce048a67fb.png">

**Comment by SamanthaWamtha** [comment]
oh yeah I figured it out! sorry I can be rly bad at finding stuff lol I appreciate it tho. it's so nice I've wanted to use this plugin for a while but ig I just couldn't find the button lol
