### ISSUE TITLE
Platform Indicators won't boot up

### ISSUE THREAD

**Issue by gameshowrecaps** [Strencher/BetterDiscordStuff#293]
![Screenshot 2022-09-16 224358](https://user-images.githubusercontent.com/57842610/190839268-3b97a0ac-cf77-4219-ab02-fc0ed0d15421.png)

**Comment by HypedDomi** [comment]
Use the latest version from PlatfomIndicators

**Comment by gameshowrecaps** [comment]
I'm late, but fixed, it was an outdated version of the plugin library.
