### ISSUE TITLE
[PronounDB] Dosn't show anywhere.

### ISSUE THREAD

**Issue by Tsumitsuki** [Strencher/BetterDiscordStuff#294]
PDB doesn't appear anywhere anymore.
the set pronouns are shown but there is no context menu anymore.

not in DMs, nor server profiles or pop-ups.

Already removed everything but PDB to make sure it's not another Plugin that brakes the menu.

Stable 148303 (2456cdb)
BetterDiscord 1.6.3

**Comment by HypedDomi** [comment]
Broken due the recent Discord Update
