### ISSUE TITLE
[PlatformIndicators] Indicators disappear after some time

### ISSUE THREAD

**Issue by HistoricTheater** [Strencher/BetterDiscordStuff#297]
Randomly, when staying in the same channel for extended periods of time the platform indicators disappear from the member list. Changing channels restores the icons until they disappear again after some time.

This is on stable 0.0.20, ptb 0.0.33, PlatformIndicators v1.4.0, a nd BD 1.7.0

**Comment by HistoricTheater** [comment]
Using BD 1.8.2 i've noticed that the updates stop when the highest role on at the time logs on. All lower tiered roles will lose their icon until they relog or add a second session(app+phone).

**Comment by PatrickSantoZZ** [comment]
same happened when u have ur DM list open and someone logs out/in that is in the top 5~ conversations. swapping tab fixed it temporary until someone logs in/out again.

**Comment by HistoricTheater** [comment]
@Strencher @HypedDomi 
Is there something to be done to offer any kinda of fix for this even in beta? The plugin is in a completely broken state after a few minutes,constantly changing channels is not a fix.

**Comment by HypedDomi** [comment]
Not that I know of. We need to wait for Strencher to release a fix

**Comment by domi-btnr** [comment]
I think that should be fixed with the recent Updates. Could someone confirm?

**Comment by domi-btnr** [comment]
Tested it and Icons didn't disappear for one hour
