### ISSUE TITLE
[PlatformIndicators] Tooltip stays

### ISSUE THREAD

**Issue by Enrico9431** [Strencher/BetterDiscordStuff#298]
Indicator Tooltip stays after clicking on it

![image](https://user-images.githubusercontent.com/85672311/193163890-7eaae957-7dc2-48ca-bdf7-bdbfb320dcfa.png)

Latest Stable version

To fix it discord has to be reloaded

**Comment by Neonights** [comment]
Same thing happens to me

**Comment by Horsion** [comment]
Also have this sometimes, not sure what causes it, might be hovering over it then alt tabbing or something. Happens infrequently, only way to fix it is reloading Discord

**Comment by ChapperNi** [comment]
happens to me too
