### ISSUE TITLE
Quick Mute Channels bug

### ISSUE THREAD

**Issue by Darwign** [Strencher/BetterDiscordStuff#3]
Sometimes when I launch discord a new mute channel button appears and it stacks up to 3 then it gets reset and does a full cycle again I don't suppose this is normal right ?
![bug](https://user-images.githubusercontent.com/47613701/79679231-c7b57d80-820c-11ea-8a09-d58818be636d.png)

**Comment by Strencher** [comment]
and when you switch channels they disappear?

**Comment by Darwign** [comment]
no if I restart they disappear and then it does the same thing all over again

**Comment by Strencher** [comment]
Do you have multiple instaces of `ZeresPluginLibrary` ?

**Comment by Darwign** [comment]
I have Xenolib, ZerePluginLibrary and MultiInstance is one of those causing it ?

**Comment by Strencher** [comment]
i think.

**Comment by Darwign** [comment]
what can I do ? since Xenolib it's needed for one of my other plugins and MultiInstance plugin it's very useful should I delete ZerePluginLibrary ?

**Comment by Strencher** [comment]
its a bug from the plugin, i'm fixing it.

**Comment by Strencher** [comment]
can you come to my [My Support Server](https://discord.gg/gvA2ree) ? there can i upload files.

**Comment by Strencher** [comment]
ill close this issue. :)
