### ISSUE TITLE
[Invisibletyping]

### ISSUE THREAD

**Issue by Ranger-4297** [Strencher/BetterDiscordStuff#30]
Doesn't actually let me enable/disable through the button on the text box
![Invistyping](https://user-images.githubusercontent.com/72880161/120242110-0749f800-c25c-11eb-8d65-25e5efebeab1.gif)

**Comment by Strencher** [comment]
Do you have an old version installed called `SilentTyping` ?

**Comment by Ranger-4297** [comment]
I have it installed however I made sure to disable it

**Comment by Strencher** [comment]
Reload your client and see if the issue still appears

**Comment by Ranger-4297** [comment]
Will do

**Comment by Ranger-4297** [comment]
Works now!
