### ISSUE TITLE
PlatformIndicators crashing Discord

### ISSUE THREAD

**Issue by xsmashx88x** [Strencher/BetterDiscordStuff#304]
platforum indicators - crashing  discord.. tho on 1.0.1018

**Comment by xsmashx88x** [comment]
> What exactly crashes discord?

platforum indicators sorry forget to add the name of the plugin, just edited the post.

**Comment by Luigi534** [comment]
I also just had the bug, I crash every time I restart, I had to completely delete the plugins from the folder to fix it because it was a looping crash

**Comment by HypedDomi** [comment]
The file is in his support server. You can also download the file from this link:
https://cdn.discordapp.com/attachments/1024261541685645332/1025867535809249340/InvisibleTyping.plugin.js

**Comment by HypedDomi** [comment]
> platforum indicators sorry forget to add the name of the plugin, just edited the post.
@xsmashx88x Do you still have this issue?
