### ISSUE TITLE
[Bug] InvisibleTyping Version: 1.2.2 broken on v1.8.2

### ISSUE THREAD

**Issue by PtrckM** [Strencher/BetterDiscordStuff#310]
Unable to load plugin using betterdiscord v1.8.2

![image](https://user-images.githubusercontent.com/54516858/197310403-c46d40fa-9773-4d8a-92af-047aad2e4746.png)

**Comment by Nova1ite** [comment]
Outdated on the BD site:
https://github.com/Strencher/BetterDiscordStuff/tree/32bd29f8e9a1f02d2310f59853f8e84b92324bda

Here's his updated one and future possible plugin fixes from selecting the "master" tree:
https://github.com/Strencher/BetterDiscordStuff/tree/master/InvisibleTyping

**Comment by PtrckM** [comment]
> Outdated on the BD site: https://github.com/Strencher/BetterDiscordStuff/tree/32bd29f8e9a1f02d2310f59853f8e84b92324bda
> 
> Here's his updated one and future possible plugin fixes from selecting the "master" tree: https://github.com/Strencher/BetterDiscordStuff/tree/master/InvisibleTyping

This is indeed working download the file https://raw.githubusercontent.com/Strencher/BetterDiscordStuff/master/InvisibleTyping/InvisibleTyping.plugin.js then reload your discord app

![image](https://user-images.githubusercontent.com/54516858/197382144-adca093b-0d1e-4cc3-a3b9-c28de5ced052.png)
