### ISSUE TITLE
[PronounDB] Can’t compile

### ISSUE THREAD

**Issue by cyrus01337** [Strencher/BetterDiscordStuff#311]
OS: Windows 10
Discord: Stable - v1.0.9007
BetterDiscord: Core v1.8.2
BDFDB (unsure if relevant): v2.9.2
PronounDB: v1.3.0

If needed I am able to send a list of all names and versions of the plugins that I use.

**Comment by fffootloose** [comment]
same here, i'm guessing the plugin just isn't updated yet?

**Comment by cigaretteaheago** [comment]
same issue for me aswell, maybe it's not updated.

**Comment by HypedDomi** [comment]
The Plugin is broken since ages. Not sure if Strencher will revive it

**Comment by HypedDomi** [comment]
Closing issue. Plugin added to [List](https://github.com/Strencher/BetterDiscordStuff/issues/324)
