### ISSUE TITLE
[ShowAllActivities] Plugin can't be compiled by BetterDiscord

### ISSUE THREAD

**Issue by FQQD** [Strencher/BetterDiscordStuff#312]
Using the newest version directly from Github, this is the error I get:

`TypeError: Cannot read property 'default' of undefined at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:261:124) at ___createMemoize___ (betterdiscord://plugins/ShowAllActivities.plugin.js:106:12) at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/ShowAllActivities.plugin.js:261:12) at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:418:40) at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:587:5) at buildPlugin (betterdiscord://plugins/ShowAllActivities.plugin.js:589:4) at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:594:2) at Object.requireAddon (<anonymous>:4:39192) at Object.loadAddon (<anonymous>:4:9163) at Object.loadAddon (<anonymous>:4:36864) at Object.loadAllAddons (<anonymous>:4:11637) at Object.initialize (<anonymous>:4:6059) at Object.initialize (<anonymous>:4:36059) at Object.startup (<anonymous>:4:396505)`

**Comment by maenDisease** [comment]
See #296
