### ISSUE TITLE
request

### ISSUE THREAD

**Issue by TheCraftedGamer** [Strencher/BetterDiscordStuff#314]
is there a way to remove pronouns from usernames or auto-hide them, I don't want mental illnesses visible to me like that on discord.

**Comment by GAbO1254** [comment]
the simples solution is not to use discord

**Comment by Technetium1** [comment]
Imagine being so mentally ill that you can't accept that there are people different from yourself. Close this ignorant waste of an issue.

**Comment by HypedDomi** [comment]
Should be possible with CSS. You can join the BetterDiscord Server and ask for CSS in the #custom-css Channel
