### ISSUE TITLE
[VoiceUserCOunter] - Not display

### ISSUE THREAD

**Issue by Soulivan71** [Strencher/BetterDiscordStuff#320]
PL version 2.0.1
Ptb 160179 (fa86f65) Host 1.0.1020 (26825) Windows 10 64-Bit (10.0.19045)

![image](https://user-images.githubusercontent.com/36502190/203260024-0189856c-92e6-43d5-b4b1-0772fde35590.png)

**Comment by HypedDomi** [comment]
Broken due the recent switch to SWC. Please use:

* #296

**Comment by Soulivan71** [comment]
So its a bd error so he is waiting for a bd fix ?

**Comment by HypedDomi** [comment]
> So its a bd error so he is waiting for a bd fix ?

No. Discord switched their compiler for performance reasons. Strencher need to update the plugin to work with the new transpiler

**Comment by Soulivan71** [comment]
Okay okay
