### ISSUE TITLE
[UnreadCountBadges] Unread count badges will not load

### ISSUE THREAD

**Issue by foursplaysroblox** [Strencher/BetterDiscordStuff#325]
![image](https://user-images.githubusercontent.com/82078139/208021697-92453679-dce1-4a65-88f7-fcafe4f0cef2.png)

**Comment by foursplaysroblox** [comment]
Ah yes nobody looked at this

**Comment by HypedDomi** [comment]
We know:
- https://github.com/Strencher/BetterDiscordStuff/issues/324
