### ISSUE TITLE
[UserDetails] Issue regarding hours

### ISSUE THREAD

**Issue by marcpinet** [Strencher/BetterDiscordStuff#33]
Hi, there is an issue regarding timestamps. Indeed, I created my account at 3pm (15h in the 24h format) but the plugin shows the 24 hours timestamp as if it was in 12h timestamp (so it shows me that I created my account at 03:00:00 which is 3am and not 3pm which should be 15:00:00.

**Comment by Strencher** [comment]
Thanks for the report, i already fixed the issue locally, i will upload it later.

**Comment by Strencher** [comment]
This should be fixed. Let me know when it the issue still exists.
