### ISSUE TITLE
How to install User Details?

### ISSUE THREAD

**Issue by lynrayy** [Strencher/BetterDiscordStuff#347]
Are you с ума сошёл там, i dont understand how to install user details plugin because there is no single plugin file

**Comment by HypedDomi** [comment]
Go to [UserDetails.plugin.js](https://raw.githubusercontent.com/Strencher/BetterDiscordStuff/master/UserDetails/UserDetails.plugin.js) and press `CTRL` + `S` and save it. After that, move the file to your Plugins folder.
*Plugin could be broken, see #324 for more Infos*

**Comment by porsche-creator** [comment]
no can't complied
