### ISSUE TITLE
Says LibaryPlugin missing

### ISSUE THREAD

**Issue by SeductiveEmo** [Strencher/BetterDiscordStuff#351]
so it says when i wanna go into settings from it that the LibaryPlugin is missing when i go into the code after i get error message.

But i have the Libary Plugin installed?
Even redownloading both doesnt help
can you please help or fix that

**Comment by HypedDomi** [comment]
Try downloading from here: https://betterdiscord.app/Download?id=9

Also which Plugin are you using which throws this Error?

**Comment by SeductiveEmo** [comment]
PronounsDB plugin lol
 
 
  On Wed, May 31, 2023 at 8:11 pm, ***@***.***> wrote:   


Try downloading from here: https://betterdiscord.app/Download?id=9

Also which Plugin are you using which throws this Error?
