### ISSUE TITLE
[Bug] PlatformIndicators Settings Don't Expand

### ISSUE THREAD

**Issue by OrniiDiien** [Strencher/BetterDiscordStuff#352]
See title. Either the settings aren't expanding or they aren't there for some reason. The chevron icon properly animates when clicked but no new content expands from the bottom.
This also occurs in another plugin that has the same style of settings window (the plugin is [removeTrackingURL](https://github.com/wotanut/DiscordStuff/blob/main/plugins/dist/removeTrackingURL.plugin.js)).
My bad if this is some overall BetterDiscord issue or something.

**Comment by Strencher** [comment]
It's an issue with ZeresPluginLibrary's Switch component. The maintainer is aware of this issue and is working on a fix.

**Comment by OrniiDiien** [comment]
Wow, quick response. Thanks!
