### ISSUE TITLE
[PlatformIndicators] Indicators not showing on profile with new usernames

### ISSUE THREAD

**Issue by Horsion** [Strencher/BetterDiscordStuff#357]
Since the switch to the new unique usernames and away from discriminators, the platform indicator doesn't show up on people's profiles. This happens with both the pop up profile from "View Profile" and the smaller one that comes up if you left click their username.
![image](https://github.com/Strencher/BetterDiscordStuff/assets/111125681/27dde00e-af16-4a39-beb2-839b53e228e7)
![image](https://github.com/Strencher/BetterDiscordStuff/assets/111125681/9a785680-aeb4-48bf-a79e-ad658988c0d3)

Also possibly related is that the platform indicator next to their name in the member list/channels does not update/come back if they go offline then online while you're in the channel, and you need to switch to another channel and then back for it to display again.
![image](https://github.com/Strencher/BetterDiscordStuff/assets/111125681/4085ac35-5a48-429b-856e-fbb357921868)

**Comment by Horsion** [comment]
Version 1.4.2 has fixed the indicators for the small profile when you left click on someone which is great! Thanks for the quick work.

However I've just noticed that the big profile that comes from right click > Profile still doesn't have the indicators. Minor issue, especially since the small one is used a lot more (At least for me), but just wondering if this was overlooked and they're handled differently or something.

**Comment by Horsion** [comment]
Oops, closed this by accident

**Comment by domi-btnr** [comment]
Fixed
