### ISSUE TITLE
[InvisibleTyping] typing disables when I switch channels

### ISSUE THREAD

**Issue by asportnoy** [Strencher/BetterDiscordStuff#36]
1. Turn on typing mode
2. Go to another channel
3. Observe the typing setting was turned off

**Comment by Strencher** [comment]
I cannot reproduce this bug, can you tell me your plugin version?

**Comment by asportnoy** [comment]
Ah, I see the issue. The exclude is per channel, whereas I thought it was global. Would be nice to have some form of global option in addition to a channel override. A per-server override would also be useful. I want the typing enabled in most channels, so having to set it for every channel gets kinda annoying.

**Comment by Strencher** [comment]
Alright, i'm gonna start working on this. I'll let you guys know when i updated it.

**Comment by Strencher** [comment]
Alright, i added those things, let me know if everything works as it should be.
