### ISSUE TITLE
ShowAllActivities broken after discord update

### ISSUE THREAD

**Issue by rrphacker** [Strencher/BetterDiscordStuff#37]
[https://github.com/Strencher/BetterDiscordStuff/blob/master/ShowAllActivities/ShowAllActivities.plugin.js](https://github.com/Strencher/BetterDiscordStuff/blob/master/ShowAllActivities/ShowAllActivities.plugin.js) is now broken because of the new discord update. Statuses are not showing anymore.

**Comment by Strencher** [comment]
It still works fine, can you tell me which release channel of discord (`Canary` | `Stable` | `PTB`) are you using?

**Comment by rrphacker** [comment]
Stable 86634 (47a4ef7)
BetterDiscord 1.1.1
Host 1.0.9002
Windows 10 64-Bit (10.0.19042)

**Comment by rrphacker** [comment]
Also, it automatically fixed itself
