### ISSUE TITLE
Setting's not working

### ISSUE THREAD

**Issue by Darkn8tT** [Strencher/BetterDiscordStuff#373]
unable to uncheck any option in the settings

**Comment by domi-btnr** [comment]
Could you provide more Infos? With which Plugin do you have this issue?

**Comment by Darkn8tT** [comment]
> Could you provide more Infos? With which Plugin do you have this issue?

APlatformIndicatorsv1.5.0 
unable to uncheck any option in the settings i click on the toggle and it animates but stays ON (green)

**Comment by domi-btnr** [comment]
The Version you use is still Beta. So there are Errors and Bugs expected. I would merge the issue with #374
