### ISSUE TITLE
[Bug] [PlatformIndicators] Settings can't be turned off

### ISSUE THREAD

**Issue by Enrico9431** [Strencher/BetterDiscordStuff#374]
Downloaded latest version here and now can't turn off any setting of it. Changing the code in the config file is to avail either as that gets reset upon reloading Discord

**Comment by domi-btnr** [comment]
Strencher is working on a Rewrite. You can try [this](https://cdn.discordapp.com/attachments/86004744966914048/1171891543930576916/APlatformIndicators.plugin.js) Version. Please keep in Mind that this Version is a Beta and can lead to Problems

**Comment by domi-btnr** [comment]
@Darkn8T @Enrico9431 Try downloading the latest Version from GitHub. Strencher fixed that Problem already.
You can find the latest Version here: https://raw.githubusercontent.com/Strencher/BetterDiscordStuff/master/PlatformIndicators/APlatformIndicators.plugin.js
