### ISSUE TITLE
ShowAllActivities is broken

### ISSUE THREAD

**Issue by VoidedGorilla** [Strencher/BetterDiscordStuff#375]
the plugin is broken, for me it just shows a bar with 2 dots under profiles.
![image](https://github.com/Strencher/BetterDiscordStuff/assets/103909928/c3ea385e-2e63-4ca3-8a6b-90bf21e0592d)

**Comment by OsmanErenN** [comment]
+

**Comment by Lemming8** [comment]
same here

**Comment by Lemming8** [comment]
![image](https://github.com/Strencher/BetterDiscordStuff/assets/42110472/3b1712ab-9669-4466-86a2-ccb41a57f107)
Line 509: ``const [UserActivityModule, method] = Webpack$1.getMangled((m) => m?.toString?.().includes("onOpenGameProfile:"));``

**Comment by Lemming8** [comment]
![image](https://github.com/Strencher/BetterDiscordStuff/assets/42110472/d84467df-5198-4d3a-8454-b25620566ba1)
Line 509: ``const [UserActivityModule, method] = Webpack$1.getMangled((m) => m?.toString?.().includes("onOpenGameProfile:"));``

**Comment by Miniontoby** [comment]
Here is a fix:

Replace the lines 312 to 314 FROM:
```js
    const activities = useStateFromStoresArray([PresenceStore], () => {
        return PresenceStore.getActivities(user.id).filter((ac) => ac.type !== 4);
    });
```

TO:
```js
    const activities = useMemo(() => {
        return PresenceStore.getActivities(user.id).filter((ac) => ac.type !== 4);
    }, [PresenceStore, user]);
```

**Comment by VoidedGorilla** [comment]
> Here is a fix:
> 
> Replace the lines 312 to 314 FROM:
> 
> ```js
>     const activities = useStateFromStoresArray([PresenceStore], () => {
>         return PresenceStore.getActivities(user.id).filter((ac) => ac.type !== 4);
>     });
> ```
> 
> TO:
> 
> ```js
>     const activities = useMemo(() => {
>         return PresenceStore.getActivities(user.id).filter((ac) => ac.type !== 4);
>     }, [PresenceStore, user]);
> ```

this worked, thank you!
