### ISSUE TITLE
[Question] Invisible typing

### ISSUE THREAD

**Issue by vilchu** [Strencher/BetterDiscordStuff#376]
Can the icon be hidden, but that the plugin will still work?
![image](https://github.com/Strencher/BetterDiscordStuff/assets/55512609/29d6eaba-deda-4dd3-9064-2111d06a666d)

**Comment by domi-btnr** [comment]
Yes. You can do that with CSS. But by doing so, you won't be able to toggle it

```css
.invisible-typing-button { display: none }
```

If you want it to be visible again, simply remove the CSS from your Quick CSS or change `none` to `block`

**Comment by vilchu** [comment]
thank you very much :)
