### ISSUE TITLE
[BUG] Platform Indicators causes crash screen on latest ptb client

### ISSUE THREAD

**Issue by iiNekoMattyii** [Strencher/BetterDiscordStuff#378]
i enable it it crashes discord on latest ptb

![image](https://github.com/Strencher/BetterDiscordStuff/assets/69323445/5e172ac5-a31c-4433-918b-046a88fb93b0)

this is my build version:

![image](https://github.com/Strencher/BetterDiscordStuff/assets/69323445/74b45002-9903-46ec-a8b1-11d8dceab260)
 (if the image is hard to read "Ptb 251515 (210edd4)")

**Comment by Nova1ite** [comment]
Same here, I could provide the error it gives me on my side
![Screenshot 2023-12-05 143238](https://github.com/Strencher/BetterDiscordStuff/assets/115776661/d9cc152f-7dc7-49df-bf20-42fd9833bf80)

**Comment by Casually-Anonymous** [comment]
I ran it on the stable version of Discord- Stable 251561 (d6757dd)- and it crashed on me too.

**Comment by iiNekoMattyii** [comment]
> Same here, I could provide the error it gives me on my side ![Screenshot 2023-12-05 143238](https://private-user-images.githubusercontent.com/115776661/288224206-d9cc152f-7dc7-49df-bf20-42fd9833bf80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDQxNDksIm5iZiI6MTcwMTkwMzg0OSwicGF0aCI6Ii8xMTU3NzY2NjEvMjg4MjI0MjA2LWQ5Y2MxNTJmLTdkYzctNDlkZi1iZjIwLTQyZmQ5ODMzYmY4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQyMzA0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTRiZDc0NDhlY2Y1MWRmMDliNmU2MmYyZDVmMTQ1YjY2ZmJiMTc4MjVkMjUwYmY2N2NiMzBlNmQ1OWUwODVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PyX1IvwHGBfTX6HEpcamvytoHt-XDbsT-WtyNStkY3Q)

ty for posting that i cant open my console without bd entirely crashing itself
