### ISSUE TITLE
[UserDetails] Time format leading zero issues

### ISSUE THREAD

**Issue by MirTeiwaz** [Strencher/BetterDiscordStuff#38]
I prefer the time format to have leading zeros (I use 24hr). 
The formatting is "year-month-day hh:mm:ss (x days ago)".

But it seems that sometimes the leading zero in time is missing whenever the "9" is present in hour, minutes, or seconds.

For example, I see "2018-02-07 00:9:30" when I want "2018-02-07 00:09:30".
I also see "2020-12-12 08:59:9" when it should have been "2020-12-12 08:59:09".
"2016-06-20 9:46:58" should be "2016-06-20 09:46:58".

So far, it seems that the problem is restricted to 9 (i.e., when it should say "09", it only says "9").
This happens on all time formats (doesn't matter if it's creation/joined/last message).

**Comment by Strencher** [comment]
i'll look into it later

**Comment by Strencher** [comment]
This has been fixed.
