### ISSUE TITLE
[Bug] PlatformIndicators internal settings cannot be opened and shows an error

### ISSUE THREAD

**Issue by Nova1ite** [Strencher/BetterDiscordStuff#384]
![Screenshot 2023-12-22 100722](https://github.com/Strencher/BetterDiscordStuff/assets/115776661/eff30f42-d34a-4c42-a831-be89f0bf16f7)
![Screenshot 2023-12-22 100733](https://github.com/Strencher/BetterDiscordStuff/assets/115776661/a4452425-5039-4df4-9f70-fab961e010f0)

**Comment by domi-btnr** [comment]
Added it to this issue: https://github.com/Strencher/BetterDiscordStuff/issues/324
I close this issue and update the other one once it gets fixed
