### ISSUE TITLE
[UserDetails] & [MessageDoubleClickActions] Not working

### ISSUE THREAD

**Issue by TheMongoloid** [Strencher/BetterDiscordStuff#39]
Your "UserDetails" & "MessageDoubleClickActions" aren't working at all for me, your other plugins seem to be working fine also, I love the "copier" plugin :)

**Comment by Strencher** [comment]
The userdetails plugin works fine on my end. Are you sure you installed ZeresPluginLibrary?

**Comment by TheMongoloid** [comment]
> The userdetails plugin works fine on my end. Are you sure you installed ZeresPluginLibrary?

I have that installed. I've just tested it on "Better Discord" and it worked fine, but I mainly use something called "Lightcord" and lightcord is where it doesn't work for some odd reason

**Comment by Strencher** [comment]
I don't support Lightcord as a platform for my plugins. Install Discord with vanilla BD and you'll get a better result since lightcord is just a stolen discord client with an old bd injection.

**Comment by TheMongoloid** [comment]
I thought you might say that, however, thanks for the advice
