### ISSUE TITLE
APlatform Indicator

### ISSUE THREAD

**Issue by Miyuki-10** [Strencher/BetterDiscordStuff#397]
i download the new version so many times, i does not work, so please stop close the issue, since it's still an issue.
if you have a solution, then send me the guide or the version that works, i even restart discord my pc, and paste in the code, it still remains the same.

![image](https://github.com/Strencher/BetterDiscordStuff/assets/93956624/30da6dfe-8707-4102-a69b-fa7e12003cc2)

**Comment by domi-btnr** [comment]
You're still on the old Version. The newest Version is `1.5.4`. The Version on the BetterDiscord Site needs to be reviewed, and then it'll point to the fixed plugin. You can bypass that when you download from [here](https://raw.githubusercontent.com/Strencher/BetterDiscordStuff/master/PlatformIndicators/APlatformIndicators.plugin.js) (`CTRL` `S`)

**Comment by domi-btnr** [comment]
If you still have issues, then write in that post and don't make a new one. I can reopen it then
