### ISSUE TITLE
QuickMuteChannels has two mute buttons

### ISSUE THREAD

**Issue by ent3r** [Strencher/BetterDiscordStuff#4]
After the recent update, there are two mute buttons. There wasnt before
![image](https://user-images.githubusercontent.com/32072697/80078424-31a48e80-854f-11ea-82a8-dffa13d8d8a2.png)

**Comment by Strencher** [comment]
which version do you have?

**Comment by ent3r** [comment]
v0.0.4

**Comment by Strencher** [comment]
can you join my Support server? There i can upload files.

**Comment by ent3r** [comment]
Sure
