### ISSUE TITLE
ChannelDMs fails to compile. Please update.

### ISSUE THREAD

**Issue by MagmaBro123** [Strencher/BetterDiscordStuff#401]

**Comment by zrodevkaan** [comment]
not happening anytime soon

**Comment by MagmaBro123** [comment]
Please remove these projects from the BD site then.

**Comment by zrodevkaan** [comment]
not my decision

**Comment by domi-btnr** [comment]
Already reported in https://github.com/Strencher/BetterDiscordStuff/issues/324

**Comment by MagmaBro123** [comment]
> Already reported in #324

That was over 2 years ago...

**Comment by zrodevkaan** [comment]
womp womp. im recreating the plugin on another mod.

channeldms probably isnt being fixed.

**Comment by domi-btnr** [comment]
> > Already reported in #324
> 
> That was over 2 years ago...

When I created the Issue, yes. But I update it occasionally. ChannelDMs is maybe broken since a year or something. And Strencher is having a life and doesnt have Time right now to fix his plugins. He will fix it when he has time and motivation

**Comment by CorePN3** [comment]
Yeah, ChannelDMs have been broken for a while. I don't expect it to be fixed. I just wish we could update the BD website.
