### ISSUE TITLE
Everything broken

### ISSUE THREAD

**Issue by domi-btnr** [Strencher/BetterDiscordStuff#408]
## Due to a recent Discord Update, all Plugins are broken. We are aware of this. Please don't create issues about it. I'll update #324 over the next Days. If you want to help, then please send the broken Plugins in this issue

**Comment by RobertoGol** [comment]
please look at line 16 it says there is an error there in the code simbol 1

**Comment by AnWoCh410** [comment]
![Screenshot 2024-06-19 101035](https://github.com/Strencher/BetterDiscordStuff/assets/173283295/ae6a2d66-4820-4e00-a8bf-135380857ca2)
As far as I know, I think the PlatformIndicators is broken entirely...

**Comment by domi-bue** [comment]
> please look at line 16 it says there is an error there in the code simbol 1

Could you elaborate which Plugin?

**Comment by domi-btnr** [comment]
> ![Screenshot 2024-06-19 101035](https://private-user-images.githubusercontent.com/173283295/341126735-ae6a2d66-4820-4e00-a8bf-135380857ca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTA0ODYsIm5iZiI6MTcxODgxMDE4NiwicGF0aCI6Ii8xNzMyODMyOTUvMzQxMTI2NzM1LWFlNmEyZDY2LTQ4MjAtNGUwMC1hOGJmLTEzNTM4MDg1N2NhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxNTE2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDUyZWE5YjRkMjhlODQyZmEwNmViNTY1NmNhOWNjOGIxZmZiZmFkMGEyN2Y4ZjBjZTU4ZGZlOTA2MzlhZmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yT8dhjNu3KNCueaL7dSIzht9HuR2mBjD6T1hwLm5AjQ) As far as I know, I think the PlatformIndicators is broken entirely...

So far yes. But @zrodevkaan is trying to fix it. There's no ETA tho, since he does it in his free time and when he has the motivation for it

**Comment by domi-btnr** [comment]
I updated the List in #324

**Comment by M0nkeyPr0grammer** [comment]
![image](https://github.com/Strencher/BetterDiscordStuff/assets/86218191/c64531f3-adbf-41a9-982b-48edd95b390f)
and 
![image](https://github.com/Strencher/BetterDiscordStuff/assets/86218191/585867e3-7fa4-439a-86be-9e0de9ed1155)

**Comment by domi-btnr** [comment]
> ![image](https://private-user-images.githubusercontent.com/86218191/341144622-c64531f3-adbf-41a9-982b-48edd95b390f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTU0NDUsIm5iZiI6MTcxODgxNTE0NSwicGF0aCI6Ii84NjIxODE5MS8zNDExNDQ2MjItYzY0NTMxZjMtYWRiZi00MWE5LTk4MmItNDhlZGQ5NWIzOTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE2MzkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMDBiMDNiZmZjZDU4MmZiOWE3NzE4MWMzNmEzMjM4MjFhOWY4MjczODkwZjQyOWZlMjdlZWMzOTA5ZGQ5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_BhSuDJshY5Cwcj96l2GDRQTX5I42H21sOe-yALU9w) and ![image](https://private-user-images.githubusercontent.com/86218191/341144705-585867e3-7fa4-439a-86be-9e0de9ed1155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTU0NDUsIm5iZiI6MTcxODgxNTE0NSwicGF0aCI6Ii84NjIxODE5MS8zNDExNDQ3MDUtNTg1ODY3ZTMtN2ZhNC00MzlhLTg2YmUtOWUwZGU5ZWQxMTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE2MzkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZDMwNzEwZWIxNWM3MjQ4OThmMTRkZWM2MThjYzM4YjA3ZmU3ZWRhZWI5NjAxYzhiZWJkM2QwNGU0YTEyYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.axKiNu6DBK9sCsE8QdPPZSuLJca_E-6dp5uOLvy9UQU)

XenoLib isn't from Strencher. ShowAllActivities is already in the List

**Comment by Andrinall** [comment]
![image](https://github.com/Strencher/BetterDiscordStuff/assets/62207048/d66212fb-6f71-4664-a5d5-e11c71f221b8)

**Comment by Riddim-GLiTCH** [comment]
> ![image](https://private-user-images.githubusercontent.com/62207048/341323422-d66212fb-6f71-4664-a5d5-e11c71f221b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzExMTIsIm5iZiI6MTcxODg3MDgxMiwicGF0aCI6Ii82MjIwNzA0OC8zNDEzMjM0MjItZDY2MjEyZmItNmY3MS00NjY0LWE1ZDUtZTExYzcxZjIyMWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA4MDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YTI5M2Y2NTkwNDQwMzc3ZDRmZjljYTdhZmUwNzMyYjFjYjU1YTkyY2JjNmFkMjllMTJlM2ZjZTYwMzhjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZsiletO4iEv1MW6d3S2zNswEp_z8YjFBVa5TvRX_Oqg)

Seems to be working fine on my end. I do have some errors, but the plugin still functions as intended.
![image](https://github.com/Strencher/BetterDiscordStuff/assets/87764384/cffd3449-81da-4bc1-8fb6-ceb87e205146)

**Comment by heyimjonas** [comment]
i digged a bit into the platform indicators and it fails due to a failed import of two packages, ColorDetails and Flux.

Flux can be fixed with this:
`Flux = Webpack.getModule(m => m?.Store);`

but the ColorDetails didn't work for me even after doing some debugging.

**Comment by avizmarlon** [comment]
![image](https://github.com/Strencher/BetterDiscordStuff/assets/24354489/6a3153de-4a3d-4112-a7a4-920f0634b8fa)


```
TypeError: Cannot read properties of undefined (reading 'Store')
    at eval (betterdiscord://plugins/APlatformIndicators.plugin.js:174:51)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

**Comment by zrodevkaan** [comment]
It would be great if people didn't high five Domi with the same issue. 

Domi and I are already aware of the Platform Indicators plugin status.

**Comment by avizmarlon** [comment]
> It would be great if people didn't high five Domi with the same issue.
> 
> Domi and I are already aware of the Platform Indicators plugin status.

It would be great if it was added to the [referred list](https://github.com/Strencher/BetterDiscordStuff/issues/324) so people would know and not bother you

**Comment by zrodevkaan** [comment]
> > It would be great if people didn't high five Domi with the same issue.
> > Domi and I are already aware of the Platform Indicators plugin status.
> 
> It would be great if it was added to the [referred list](https://github.com/Strencher/BetterDiscordStuff/issues/324) so people would know and not bother you

Reading the other replies is a good area to start. Not countering with add the issue to a 2 year old post.

**Comment by Alicyl** [comment]
![Discord_C1QR6wqRaY](https://github.com/Strencher/BetterDiscordStuff/assets/13776859/f119dcac-63b9-4717-9aeb-5f52cd181144)

**Comment by jonesy-b-dev** [comment]
I get this error
```js
TypeError: Cannot read properties of undefined (reading 'Store')
    at eval (betterdiscord://plugins/APlatformIndicators.plugin.js:174:51)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
```

**Comment by domi-btnr** [comment]
> I get this error
> 
> ```js
> TypeError: Cannot read properties of undefined (reading 'Store')
>     at eval (betterdiscord://plugins/APlatformIndicators.plugin.js:174:51)
>     at N.requireAddon (betterdiscord/renderer.js:5:28601)
>     at N.loadAddon (betterdiscord/renderer.js:5:6221)
>     at N.loadAddon (betterdiscord/renderer.js:5:26269)
>     at betterdiscord/renderer.js:5:4201
> ```

We’re working on a fix. If you want, you can try the dev build. It’s in strenchers server

**Comment by domi-btnr** [comment]
The List with the Broken Plugin has been updated and can be viewed in #324
