### ISSUE TITLE
[InvisibleTyping] Enhancement suggestions.

### ISSUE THREAD

**Issue by QuickNET-Tech** [Strencher/BetterDiscordStuff#41]
First I would like to thank you for this improved version of SilentTyping, it's much appreciated.  
Secondly I think there's a few enhancements I would like to see:
- An option to toggle typing in all DMs (this is assuming it's possible to enumerate a complete list of DMs)
- A setting to set the default state of typing in newly created DMs and newly joined servers to either "Typing Enabled" or "Typing Disabled"
- A right-click menu item to toggle typing for all channels in a given server (e.g. Right click server icon -> Click "[Enable/Disable] Typing")
- A popup or warning of some kind that lets a user know that SilentTyping should be uninstalled if it's present and discord should be reloaded. I ran into some issues with the plugin initially after only disabling SilentTyping which lead to it seeming to be broken and I imagine others may experience this as well

**Comment by Strencher** [comment]
This should be fixed/added after the latest updates. Reopen this issue if it still occurs.
