### ISSUE TITLE
"Disable Globally" doesn't actually work

### ISSUE THREAD

**Issue by Eray761** [Strencher/BetterDiscordStuff#417]
If you use "Disable Globally" it will change the icon to disabled typing but it will still type, and when you click on it again to change it to enabled typing icon it will not show you typing

**Comment by domi-btnr** [comment]
I fixed that yesterday:


https://github.com/user-attachments/assets/4a8343b9-4bbc-4f16-b284-ee3cc330b84e



The Logic is like this:
> The Plugin only saves Channel where you changed the Setting in a List. It doesnt have any info if it was disabled or enabled. Its always the opposite of the global setting
So when you change the Setting for this Channel and your Global Config is enabled then it will be disabled for this channel
