### ISSUE TITLE
[InvisibleTyping] Disable per channel works, but global doesn't!

### ISSUE THREAD

**Issue by SoyRA** [Strencher/BetterDiscordStuff#418]
Since the plugin started working again (because I got a window saying that xd) I noticed that it doesn't work like before.

- **If I enable/disable per channel:** I see that it works perfectly.
- **If I enable/disable global:** it always shows that I'm writing, no matter what.

I've tried removing the plugin and its config, restarted Discord, reinstalled (v1.3.4) and still no way to recover the old behavior: it's not seen in any channel / group / PM / whatever I'm typing.

***

```json
{
    "settings": {
        "lastVersion": "1.3.4",
        "autoEnable": false
    }
}
```

True or false gives the same result, the only thing that causes what I want ( not showing that I'm typing) is when `"exclude": []` exists with the channel I added.

**Comment by domi-btnr** [comment]
Update to 1.3.5. Redownload from GitHub
