### ISSUE TITLE
Update ChannelDms. It won't load.

### ISSUE THREAD

**Issue by MagmaBro123** [Strencher/BetterDiscordStuff#419]
Title. If this isn't being updated, please remove it from the BD site.

![image](https://github.com/user-attachments/assets/669eb4b6-fee0-486c-a5c2-cdab23f36dcc)

**Comment by Riddim-GLiTCH** [comment]
Have you seen [the pinned issue](https://github.com/Strencher/BetterDiscordStuff/issues/324)? We are currently aware of all plugins being broken. This exact plugin is listed.
