### ISSUE TITLE
[INVISIBLETYPING] Disabling the "Automatically enable" setting fails to disable typing by default

### ISSUE THREAD

**Issue by doqfgc** [Strencher/BetterDiscordStuff#420]
It also desyncs the graphic; the "typing on" graphic disables typing, and vice-versa.

**Comment by domi-btnr** [comment]
On what Version are you on? The issue described was a known bug in 1.3.4 and prior. That should be fixed in 1.3.5

**Comment by doqfgc** [comment]
Ah, it looks like I'm on 1.3.4 and have not received the .5 update. Had to patch manually. All good!
