### ISSUE TITLE
[Bug]: Platform Indicators entirely broke

### ISSUE THREAD

**Issue by iiNekoMattyii** [Strencher/BetterDiscordStuff#425]
### Plugin

Platform Indicators

### Bug Description

it gives an error at startup and doesn't work
![image](https://github.com/user-attachments/assets/b7ce4683-e1a0-4f05-a93f-f9be40fcca9e)

### Confirmation

- [X] I am using the latest version of the plugin
- [X] This issue has not already been reported

**Comment by zrodevkaan** [comment]
This is known. There is already a fix out.

https://github.com/Strencher/BetterDiscordStuff/commit/d79c24df596150c2d4ddc32d15b661c3de1aa8ce

**Comment by iiNekoMattyii** [comment]
alright thank you
