### ISSUE TITLE
[Bug]: [UserDetails] error at startup

### ISSUE THREAD

**Issue by madmax17** [Strencher/BetterDiscordStuff#426]
### Plugin

UserDetailsv2.9.1by Strencher

### Bug Description

Error at startup "An error was encountered while trying to load this plugin."

### Confirmation

- [X] I am using the latest version of the plugin
- [X] This issue has not already been reported

**Comment by domi-btnr** [comment]
Please see https://github.com/Strencher/BetterDiscordStuff/issues/324
