### ISSUE TITLE
[Bug]: [StatusEverywhere] error on startup

### ISSUE THREAD

**Issue by madmax17** [Strencher/BetterDiscordStuff#427]
### Plugin

StatusEverywherev2.3.5by Strencher, Zerebos

### Bug Description

An error was encountered while trying to load this plugin.

### Confirmation

- [X] I am using the latest version of the plugin
- [X] This issue has not already been reported

**Comment by domi-btnr** [comment]
Please see https://github.com/Strencher/BetterDiscordStuff/issues/324
