### ISSUE TITLE
[UserDetails] "Source"-Link in plugin overview not working

### ISSUE THREAD

**Issue by mamasch19** [Strencher/BetterDiscordStuff#45]
If you click on the GitHub icon in the BetterDiscord settings, it leads you to https://github.com/Strencher/BetterDiscordStuff/UserDetails which isn't available. It should probably rather open https://github.com/Strencher/BetterDiscordStuff/tree/master/UserDetails which is the plugin's GitHub page. 

Not a huge deal but I felt like some people could get confused by that.

**Comment by HypedDomi** [comment]
Fixed
