### ISSUE TITLE
InvisibleTyping is too limited

### ISSUE THREAD

**Issue by ARyOtaRe** [Strencher/BetterDiscordStuff#48]
[InvisibleTyping]
More a suggestion than an error, but set the invisible typing to false and/or enable per category blacklisting

**Comment by CorneliusCornbread** [comment]
Yeah it being typing being disabled by default everywhere is really annoying, an option to configure it would be nice

**Comment by HypedDomi** [comment]
Added. Rightclick the Icon to enable/disable it globally
