### ISSUE TITLE
[Copier] Don't copy role id

### ISSUE THREAD

**Issue by ProgrammindDev** [Strencher/BetterDiscordStuff#49]
Hello, I found a small bug in the plugin.
When I try to copy a role id, nothing is in the clipboard
This is a bug on line 1072 where instead

https://github.com/Strencher/BetterDiscordStuff/blob/88d65164254f49bf7a7b3edbccdd8a9d9a6237d1/Copier/Copier.plugin.js#L1072

Should be 
`
 ElectronModule.copy(role.id); `

**Comment by Strencher** [comment]
I'm sorry for that. Do you mind doing a PR for that issue? Don't forget to bump the version number.
