### ISSUE TITLE
[UserDetails] Activity Icons Break Popout

### ISSUE THREAD

**Issue by MulverineX** [Strencher/BetterDiscordStuff#50]
Left-clicking on users in the member list while Activity icons are on does nothing, once disabled it works again. On Canary/Powercord

**Comment by Strencher** [comment]
Hmm, it works fine for me. Could you take a look at your console and tell me if it's showing any error messages?
![YCCIE4FrfO](https://user-images.githubusercontent.com/46447572/122666084-76f03a80-d1ab-11eb-9bcb-4a24e7d24bec.gif)

**Comment by bghyt** [comment]
> Hmm, it works fine for me. Could you take a look at your console and tell me if it's showing any error messages?
> ![YCCIE4FrfO](https://user-images.githubusercontent.com/46447572/122666084-76f03a80-d1ab-11eb-9bcb-4a24e7d24bec.gif)

I have the same issue i believe they are referring to this 
![image](https://user-images.githubusercontent.com/13301381/127387362-f3268fe2-8d11-4581-a255-8a48521713d1.png)

**Comment by Strencher** [comment]
No, you need to follow #63.

**Comment by Strencher** [comment]
Closing this due to lack of information.
