### ISSUE TITLE
[UserDetails] Plugin icons not visible

### ISSUE THREAD

**Issue by asorel1942** [Strencher/BetterDiscordStuff#52]
Icons for user details are invisible. Have attempted to disable and then re-enable plugin, followed by restarting Discord, with no change in behavior.
![image](https://user-images.githubusercontent.com/33983895/123998444-80458800-d99f-11eb-9f2c-85bd28b9f8da.png)

Discord build info:
![image](https://user-images.githubusercontent.com/33983895/123998516-8e93a400-d99f-11eb-82ff-d3730fb11612.png)

**Comment by RadNotRed** [comment]
It appears you are on an outdated version, you can download a working version here: https://strencher.github.io/download/?plugin=UserDetails
