### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Social-Interactive** [Strencher/BetterDiscordStuff#55]
![Screenshot 2021-07-04 153956](https://user-images.githubusercontent.com/72802595/124387416-e05d6680-dcde-11eb-962d-50a87fdc5c1c.png)

Failed to fetch, problem on every profile

**Comment by Strencher** [comment]
It works fine for me. Can you open your console `Ctrl + shift + i` and tell me if there's an error __related__ to UserDetails?

**Comment by Strencher** [comment]
I'm closing this due to no response from the author.
