### ISSUE TITLE
Fatal Crash Loop On User Details

### ISSUE THREAD

**Issue by werewolfboy13** [Strencher/BetterDiscordStuff#59]
[CrashRecovery] HEY OVER HERE! Show this to the plugin developer or in the support server!
Prettified stacktraces, stack:
 TypeError: Cannot read property 'messages' of undefined
    at injectStrings (betterdiscord://plugins/UserDetails.plugin.js:1948:48)
    at Set.forEach (<anonymous>)
    at Set.forEach (<anonymous>) 
Component stack:
     in RouteWithImpression
    in t
    in div
    in div
    in div
    in AppView
    in div
    in AnimatedComponent
    in Layer
    in div
    in TransitionGroup
    in Layers
    in ConnectedLayers
    in div
    in Shakeable
    in Chat
    in t
    in t
    in ViewsWithMainInterface
    in FluxContainer(ViewsWithMainInterface)
    in Suspense
    in d
    in t
    in t
    in div
    in ModalProvider
    in LayerProvider
    in VerificationLayerProvider
    in LayerProvider
    in AppLayerProvider
    in FocusRingScope
    in ErrorBoundary

**Comment by Strencher** [comment]
This should be fixed in the [Latest commit](https://github.com/Strencher/BetterDiscordStuff/commit/3a57e20e1a2c42eb8d663b3208a74388788fd306)

**Comment by werewolfboy13** [comment]
I will test it.

**Comment by werewolfboy13** [comment]
Verified fix. Thanks for the quick response! Closing issue.
