### ISSUE TITLE
["Bug"] You forgot a detail

### ISSUE THREAD

**Issue by NzoSifou** [Strencher/BetterDiscordStuff#6]
Hello !

If a user limit is defined on channels, you forgot to "deactivate" your counter: 
![image](https://user-images.githubusercontent.com/54418244/82557978-040e2d80-9b6d-11ea-8d8d-4c03669c6267.png)

**Comment by Strencher** [comment]
okay

**Comment by Strencher** [comment]
i've created a new branch with an new version of the plugin. Can u please test [this version](https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/Strencher/BetterDiscordStuff/testing/VoiceUsersCounter/VoiceUsersCounter.plugin.js) if they works?

**Comment by Kytoh** [comment]
Nice
With that is solved
