### ISSUE TITLE
[PlatformIndicators]

### ISSUE THREAD

**Issue by DiR3KT** [Strencher/BetterDiscordStuff#60]
When using PlatformIndicators and Compact message display mode, timestamps get mashed with username in chat.

### Compact Mode
![Compact messages](https://user-images.githubusercontent.com/8590287/126040461-0e772c3d-106f-46e8-98f3-42d10dc2cd46.png)
### Normal Mode
![Normal messages](https://user-images.githubusercontent.com/8590287/126040464-ed0f921f-acd2-40fd-be3e-19ece9b96408.png)

Also, I'm using forced 24H format (English, UK), I don't know if it matters

**Comment by Strencher** [comment]
I'll push an update later.

**Comment by TheFurryDevil** [comment]
I hope you didn't forget about us compact mode users :/

**Comment by Snaping14** [comment]
Nudge 
For context, I use compact mode and I'm surprised he hasn't fixed this yet... When is this "later" coming @Strencher ?

**Comment by Snaping14** [comment]
Because this was the first thing I came across when trying to fix the issue, this is the fix provided by Strencher's discord staff that worked for me. :D
```
.compact-2Nkcau .PI-indicatorContainer svg {
    display: block;
    margin-left: 0;
}

.compact-2Nkcau .PI-indicatorContainer {
    margin-bottom: 2px;
    margin-left: -4px;
    margin-right: 3px;
}
```
