### ISSUE TITLE
[TwitchChatV2] Broken?

### ISSUE THREAD

**Issue by GoldenMyst** [Strencher/BetterDiscordStuff#61]
When I type in the user and click open, it shows nothing. I tried copy & pasting and manual typing it out but it still doesn't seem to function correctly. I checked if they were online and they were. I also tried ctrl+r but it also didnt solve the issue.

![Screenshot_48](https://user-images.githubusercontent.com/74118946/126273598-d3e80c5e-1fc1-4b04-985d-90b563f54ec3.png)

**Comment by Strencher** [comment]
Yes, it's broken and also deprecated. I'll remove it later.
