### ISSUE TITLE
VoiceChatNotifications not loading

### ISSUE THREAD

**Issue by raffel080108** [Strencher/BetterDiscordStuff#68]
Everytime I start discord it gives me an error message, that VoiceChatNotifications could not be loaded
![Screenshot (303)](https://user-images.githubusercontent.com/62069283/127262073-50b14dde-6d88-46a7-8185-ab1e21182505.png)
Could you please fix this or tell me how to fix it myself? Thanks! 😄

**Comment by RadNotRed** [comment]
redownload and ctrl r
