### ISSUE TITLE
[LinkChannels] suggestion: add vc's

### ISSUE THREAD

**Issue by GenesisAria** [Strencher/BetterDiscordStuff#69]
As title says, i don't see it adding the link for voice channels.

**Comment by Strencher** [comment]
Back to when it wasn't possible to link vc's, i had to add this filter which basically removes it for voice channels. <https://github.com/Strencher/BetterDiscordStuff/blob/development/LinkChannels/LinkChannels.plugin.js#L132>
Anyways, yeah that's planned just not sure if i remove the filter if something else breaks.
