### ISSUE TITLE
[StatusEverywhere] About me hidden until loaded

### ISSUE THREAD

**Issue by howlagon** [Strencher/BetterDiscordStuff#71]
While using StatusEverywhere v2.0.0 and ZeresPluginLibrary v1.2.31, clicking on someone's profile in chat doesn't show their **About Me** section or their proper banner (sometimes) until you load it (either from viewing their entire profile or from the member list)

**Affected Versions:**
BetterDiscord 1.2.1
Discord Canary 92460 (28fdee6)

**Steps:**
1. Reload Discord with StatusEverywhere v2.0.0 in non-streamer mode.
2. Click on _somebody else's_ profile in chat (not in the member list)

To get the **About Me:**
1. Click on _somebody else's_ profile in either the member list or the large profile
If the user's chat profile is still open as you do this, you can watch both the banner and about me appear/change.

**Expected outcome:** 
The **About Me** section showing up without it needing to be loaded first.
![image](https://user-images.githubusercontent.com/24992550/128292717-ad7464fa-0c17-409a-a946-679e9636ef9d.png)

**Actual outcome:** 
The **About Me** section doesn't appear before it is loaded and stored prior.
From chat:
![image](https://user-images.githubusercontent.com/24992550/128292765-19ade37b-1f31-4e4d-b459-8814690d8d37.png)
From profile:
![image](https://user-images.githubusercontent.com/24992550/128292835-ec961a3c-a1a2-48cc-a740-446e9825ebd3.png)
From chat (after loading the about me):
![image](https://user-images.githubusercontent.com/24992550/128292934-18d6c7fd-f5ac-4bc3-b5b2-222ba8f1c897.png)

**Comment by Strencher** [comment]
Thanks for the report, i'll look into the issue, but i think it's an issue with [`ZeresPluginLibrary`](http://github.com/rauenzi/BDPluginLibrary), since i'm using `Popout.showUserPopout` to open it. I'll see and may contact Zerebos about the issue.

**Comment by ElySway007** [comment]
![image](https://user-images.githubusercontent.com/74378678/159054867-6396fbe9-0b9c-47e4-8565-c1fd26ff0a17.png)
bug chat channel

**Comment by HypedDomi** [comment]
Fixed
