### ISSUE TITLE
[Copier] Copy DM Channel ID

### ISSUE THREAD

**Issue by itsmeboy0** [Strencher/BetterDiscordStuff#72]
Right now, when I click on a DM channel and click Copy > ID, I get the ID of the user instead of a DM channel. It would be useful if there was an option to copy the DM channel ID itself.

**Comment by Strencher** [comment]
Added in https://github.com/Strencher/BetterDiscordStuff/commit/37cdd7a356a9d8efa5e5270b4cbaa6bfe8282dec. 👍

**Comment by itsmeboy0** [comment]
Thanks, it works well.
