### ISSUE TITLE
[UnreadCountBadges] Please include muted categories to muted channels

### ISSUE THREAD

**Issue by rakosi2** [Strencher/BetterDiscordStuff#78]
Could you please add all channels under a muted categories to the `Include Muted Channels of Guilds` settings.

**Comment by TheHunter1234** [comment]
Please, I actually removed the plugin because I am in a lot of servers and I don't have the time to blacklist every channel I don't want or mute channels, like bot channels.

**Comment by Strencher** [comment]
I actually implemented that, but for some reason i done the check wrong. 🤦 I'll fix it in the next update!

**Comment by Strencher** [comment]
This has been fixed in the latest commit https://github.com/Strencher/BetterDiscordStuff/commit/4a1087f5e9fe048e7917ee188f9916e62b3962ad. Please let me know if something is still broken about that.
