### ISSUE TITLE
[Feature] Ability to open user profile in spotify app

### ISSUE THREAD

**Issue by some0ne3** [Strencher/BetterDiscordStuff#8]

**Comment by Strencher** [comment]
already added.

**Comment by some0ne3** [comment]
ok, so it's not working for me :/

**Comment by Strencher** [comment]
can u send me the link u trying to open?

**Comment by some0ne3** [comment]
https://open.spotify.com/user/w4d73fjmt4tdn5spvhy3ewhoi

**Comment by some0ne3** [comment]
it opens in my browser instead of spotify

**Comment by Strencher** [comment]
okay. did you try to reload via `Ctrl + R`

**Comment by some0ne3** [comment]
yes, problem still exists

**Comment by Strencher** [comment]
![image](https://i.imgur.com/Ykre59Y.gif)

**Comment by Strencher** [comment]
which os do you have?

**Comment by some0ne3** [comment]
but i open it from user's profile - i forgot to note

**Comment by some0ne3** [comment]
windows 10

**Comment by Strencher** [comment]
ahh

**Comment by some0ne3** [comment]
Is there a way to add this or not?

**Comment by Strencher** [comment]
yes

**Comment by Strencher** [comment]
can u try [this version](https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/Strencher/BetterDiscordStuff/testing/OpenSpotifylinksInSpotify/OpenSpotifylinksInSpotify.plugin.js) out?

**Comment by some0ne3** [comment]
Yes, it works now, thanks :)
