### ISSUE TITLE
[BetterBannedUsers v1.0.1] Using Forward Slash Causes Discord Crash

### ISSUE THREAD

**Issue by sinnx3** [Strencher/BetterDiscordStuff#80]
Starting a conversation in the text input box with a forward slash causes the entire discord application to crash (yes I've disabled all my plugins one by one to find out it is this one causing it)

**Comment by sinnx3** [comment]
![Discord_QSifNI72pJ](https://user-images.githubusercontent.com/3137441/131780421-7eb049a9-01a2-4d61-817b-627d2e3ada29.png)
If I were to delete the period the application would crash / trigger a restart.

**Comment by Strencher** [comment]
This has been fixed.
