### ISSUE TITLE
Unread showing on muted channels

### ISSUE THREAD

**Issue by Masono03** [Strencher/BetterDiscordStuff#83]
For the Unreadcounter it shows on muted channels too even tho i made sure that this sint turned on. I am on the newest Canary build.

**Comment by Strencher** [comment]
I can't reproduce that, it doesn't show it on muted channels unless i go into the channel (which is on purpose).

**Comment by Strencher** [comment]
You need to enable this for now.
![image](https://user-images.githubusercontent.com/46447572/132108939-7efb3409-3426-4f30-8ca7-f2125c5d216b.png)

**Comment by HypedDomi** [comment]
Closed due to inactivity.
