### ISSUE TITLE
Giant space in profile settings

### ISSUE THREAD

**Issue by Triple4s** [Strencher/BetterDiscordStuff#85]
It correlates with "Alexis Modern Discord Theme"

![Screenshot (4930)_LI](https://user-images.githubusercontent.com/87712211/133622495-4a52f64c-8674-437b-a73b-aa1306777f93.jpg)

**Comment by Strencher** [comment]
What plugin is it about?

**Comment by Triple4s** [comment]
The "StatusEverywhere" one

**Comment by Strencher** [comment]
Well, it works fine without the theme so i'd say tell the theme dev to fix it since i don't know how he's handling stuff.

**Comment by Triple4s** [comment]
I already did, but I'm still waiting for an answer

**Comment by AlexisJonsson** [comment]
@Triple4s 

I managed to fix the issue in my theme so it's available now in its latest update!
