### ISSUE TITLE
[StatusEverywhere] Blurred user avatar & audit log is not working

### ISSUE THREAD

**Issue by orblazer** [Strencher/BetterDiscordStuff#88]
Hello,

## Blurred user avatar
With the last discord update the user avatar is blurred like that :
![Screenshot_20210925_095647](https://user-images.githubusercontent.com/1344792/134764025-7f931657-d696-4273-a0f2-2848f2a6536f.png)

## Audit log

In the console log i have :
```
Uncaught (in promise) TypeError: Cannot read property 'prototype' of undefined
    at StatusEverywhere.patchAuditlog (betterdiscord://plugins/StatusEverywhere.plugin.js:1300)
    at betterdiscord://plugins/StatusEverywhere.plugin.js:906
    at betterdiscord://plugins/0PluginLibrary.plugin.js:3373
    at StatusEverywhere.onStart (betterdiscord://plugins/StatusEverywhere.plugin.js:907)
    at StatusEverywhere.start (betterdiscord://plugins/0PluginLibrary.plugin.js:6466)
    at Object.startPlugin (<anonymous>:4:231836)
    at Object.startAddon (<anonymous>:4:231631)
    at Object.loadAddon (<anonymous>:4:192820)
    at Object.loadAddon (<anonymous>:4:229804)
    at Object.loadAllAddons (<anonymous>:4:194920)
    at Object.initialize (<anonymous>:4:189410)
    at Object.initialize (<anonymous>:4:229014)
    at Object.startup (<anonymous>:4:291165)
```

The line throw that error : https://github.com/Strencher/BetterDiscordStuff/blob/b863c6dbce6b4fa2a075a5be829d89a33829dab0/StatusEverywhere/index.tsx#L443

## Versions
- StatusEverywhere: v2.0.0
- ZeresPluginLibrary: v1.2.32
- BetterDiscord: 1.2.1
- Discord Stable: 99016 (0d5a801)

Thanks.

**Comment by Strencher** [comment]
I can reproduce both issues shown, I'm working on a fix right now which i can hopefully push in about an hour. Thanks for submitting the issue.

**Comment by Strencher** [comment]
Fixed in https://github.com/Strencher/BetterDiscordStuff/commit/fddaebd4ea7190e572feb2b910e8393096f2041e

**Comment by Strencher** [comment]
Huh, what's your current version?

**Comment by JadeMin** [comment]
ive been having the same issue for a very long time.

Discord : PTB 108924 (eb8c571)
BD : 1.3.0
StatusEverywhere : 2.2.0

**Comment by JadeMin** [comment]
not sure if this is an error that'll helps solve the problem but
![Capture](https://user-images.githubusercontent.com/36400787/147828405-32c75875-c913-47a7-813a-bb0339888db1.PNG)

**Comment by JadeMin** [comment]
![캡처](https://user-images.githubusercontent.com/36400787/147829144-06657872-154d-45af-8a05-8d81109bca58.PNG)
oh...

**Comment by orblazer** [comment]
Oh thanks for the solution :D hand the default size of discord use `80px`
