### ISSUE TITLE
Quick mute buttons beeing duplicated

### ISSUE THREAD

**Issue by Darkissou** [Strencher/BetterDiscordStuff#9]
QuickMuteChannels seems to have it's buttons to mute channels duplicated. It seems to appear randomly, as I didn't saw the duplicated buttons directly after I installed the plugin

![image](https://user-images.githubusercontent.com/57590802/83960745-95c7ab80-a88c-11ea-8084-293de5ed5efe.png)

I know there was already some issues opened but there's not any fix already so I'm posting it back

**Comment by Strencher** [comment]
can u try [this](https://cdn.discordapp.com/attachments/686276979221069854/719086366272651274/QuickMuteChannels.plugin.js) version out?

**Comment by Strencher** [comment]
closed due to inactive

**Comment by Darkissou** [comment]
Bruh I wasn't able to test it cause I wasn't using my pc the whole time

**Comment by Strencher** [comment]
you didn't say anything after 2 weeks. so i closed this. if you are on your pc comment on this & ill reopen it.

**Comment by rikusen0335** [comment]
That works for me well.

**Comment by GiraffeCubed** [comment]
> 
> 
> can u try [this](https://cdn.discordapp.com/attachments/686276979221069854/719086366272651274/QuickMuteChannels.plugin.js) version out?

This was definitely a problem, I constantly had to disable the plugin and only enable it when joining a new server for the convenience. The version you linked seems to have solved the duplicate item issue, hopefully this gets pushed to main release.

**Comment by Strencher** [comment]
okay. ill push it when the new BBD beta was merged & i need to uodate all my plugins.

**Comment by Strencher** [comment]
Fix was merged so i'll close this one.
