### ISSUE TITLE
[Copier] - Add Support For Threads

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Strencher/BetterDiscordStuff#94]
Hi, Please add support for threads to copy ID, Mention
![Screen Shot 2021-10-03 at 12 13 26 am](https://user-images.githubusercontent.com/2242880/135720323-56a0d7b9-e178-49cd-b328-67fb6f831fbe.jpg)
I want to be able to copy the ID/mention of threads without pulling it manually via a message link.

**Comment by Strencher** [comment]
Added in https://github.com/Strencher/BetterDiscordStuff/commit/7a3d4ef04656e3cb8600ebf46a05072ea56659c6
